### ISSUE TITLE
[BUG] On the Drive Failure Recovery page, step 4 is mislabeled step 1

### ISSUE THREAD

**Issue by wdinyes** [minio/docs#1001]
**Describe the bug**
On the Drive Failure Recovery page, step 4 is mislabeled step 1.  Honestly, this is a small enough bug that it doesn't have mucb more of a desciption.

**To Reproduce**
1. Click on the [Remount The Drive](https://min.io/docs/minio/linux/operations/data-recovery/recover-after-drive-failure.html#remount-the-replaced-drive-s) step
2. Notice that the step is labelled as 4, when it should be 1.
3. The issue is also in the right hand side TOC area (but is probably auto-gennerated from the main content anyway)

**Expected behavior**
Well, it'd be nice if it was step 4.

**Screenshots**
<img width="1096" alt="Screenshot 2023-09-13 at 10 07 23 AM" src="https://github.com/minio/docs/assets/25906104/e16501a9-9111-4827-a9fc-3989212a15cd">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 116

**Comment by ravindk89** [comment]
Anyone performing this procedure with a Delorean and enough runway to hit 88MPH could do this tutorial in the stated order, but I see your point @wdinyes . We'll patch this up
