### ISSUE TITLE
Missing documentation for heal status colors

### ISSUE THREAD

**Issue by zeeZ** [minio/docs#1005]
`mc admin heal` and the web console's Monitoring/Drives page report a status of Green, Yellow, Red and Grey.

Neither the various documentation pages linked on the drives page, the mc command, nor the online documentation explain what those colors imply. Searching for these terms on min.io yields no results.

Either those colors should be documented somewhere, or the output of those commands could be changed to a more meaningful textual representation of what those colors are meant to imply.

Currently one has to speculate, rely on tribal knowledge or dig through the source code in order to add meaning to the output.

**Comment by ravindk89** [comment]
https://github.com/minio/mc/pull/4682#pullrequestreview-1631608240

SO our intent at this point is as follows:

- The Red-Yello-Green-Grey format was designed a long time ago, and doesn't provide a ton of useful data anymore
- We will hide the majority of `mc admin heal` options as they are difficult to interpret outside of engineering-led debugging
- We will explore providing real-time metrics for `mc admin heal` similar to what you can get from `mc admin trace --call heal` or monitoring [healing metrics](https://min.io/docs/minio/linux/operations/monitoring/metrics-and-alerts.html#healing-metrics)

**Comment by ravindk89** [comment]
From a docs perspective we'll add a deprecation warning around the older format of display output, simple guidance on what the output intent was, and guidance to use the debugging-focused params w/ engineering guidance.

**Comment by djwfyi** [comment]
Covering this as part of work on #1009 .
