### ISSUE TITLE
[RELEASE] MinIO Server release 2023-09-27T15-22-50Z

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#1016]
- [ ] Add info about tiering not requiring versioning ([PR #18108](https://github.com/minio/minio/pull/18108))

Something along the lines of the following at https://min.io/docs/minio/linux/administration/object-management/object-lifecycle-management.html#object-transition-tiering:

```
Starting with version X, MinIO no longer requires the remote tier to have versioning enabled.

Prior to X, you must enable versioning on the remote *and* ensure the provided remote access credentials have permissions to perform versioned operations.
```

**Comment by feorlen** [comment]
Maybe this is https://github.com/minio/minio/pull/18108 ? 
tier: Avoid doing versioned operations since not required anymore

**Comment by djwfyi** [comment]
Yeah, I updated the description. Thanks for the catch, @feorlen .

**Comment by feorlen** [comment]
The versioned-or-not question could be a previous miscommunication. The behavior seems always (-ish) to have been like this, but not well explained. @vadmeste is confirming.

Perhaps something like this:
> The remote bucket may be versioned or not. If it is versioned, you must have s3:DeleteObjectVersion and s3:GetObjectVersion permissions.
