### ISSUE TITLE
[FEATURE] Add documentation on Stripe Size setting

### ISSUE THREAD

**Issue by wdinyes** [minio/docs#1024]
**Is your feature request related to a problem? Please describe.**
We clearly show that changing the stripe size for Erasure Code is a possibility on our erasure code calculator, but the variable and process for doing so is undocumented anywhere.  This is irksome to me on many levels.

**Describe the solution you'd like**
Adding the [redacted] to the list of environment variables on this [page](https://min.io/docs/minio/linux/reference/minio-server/minio-server.html) would be an ideal solution.  I don't think we should document it elsewhere, as it's really for advanced users, but we also shouldn't try to hide it.  That said, a substantial warning and some note on the implication that this cannot be changed once a cluster is active would probably be advisable.

**Describe alternatives you've considered**
Uh . . . keeping my big yap shut and not complaining about it?  But . . . I don't like that solution.  I suppose we could put the content elsewhere.  There's also the fact that this can have negative impacts, so we probably ought to put a "talk to us on Subnet first" warning on it.

**Additional context**
I was really just working on completing my Erasure Code deck, and had just added the standard storage class environment variable when I realized I have a whole slide discussing stripe sizes and that it is technically possible to change it from the default, but that there was no documentation anywhere (apart from combing through the source code) about the variables needed to change the stripe size.  If I have to comb through the code to find a setting, I, as an end user, am clearly too over-confident in my abilities and therefore will absolutely use this setting incorrectly.  Much better to have it documented at least somewhere, even if we put huge warnings on it.  In fact, I'd prefer having well documented warnings, precisely because our source code doesn't really warn folks against using it much.

**Comment by wdinyes** [comment]
On the advice of counsel, we should not document this.

**Comment by feorlen** [comment]
To expand on the previous comment, messing with this setting is very much not recommended. Practical use cases are rare and incorrect use likely to irreparably damage a deployment.
