### ISSUE TITLE
Doc update needed for PR github.com/minio/mc/pull/4715

### ISSUE THREAD

**Issue by zveinn** [minio/docs#1036]
There is a new --retry flag potentially being added to mc mirror

**Comment by ravindk89** [comment]
Thanks for the heads up @zveinn !

We also track releases for `mc` and create issues as-needed if an item needs docs - I'll have to chat w/ Kannappan at some point on something more formal for our purposes

**Comment by ravindk89** [comment]
Will do this as part of #1045
