### ISSUE TITLE
[BUG] invalid namespace in docs for deploying tenant

### ISSUE THREAD

**Issue by shanshanying** [minio/docs#1041]
doc link: https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-operator-helm.html#deploy-a-tenant
<img width="775" alt="image" src="https://github.com/minio/docs/assets/111829739/23c02e91-f413-429a-95a9-5d38b7e4a2ae">

The namespace `Tenant-ns` in invalid. Should it be `tenant-ns` instead?

**Comment by feorlen** [comment]
That's odd, in my notes it's even `t`. Thank you for reporting that @shanshanying !
