### ISSUE TITLE
Document upgrading Helm-deployed Operator and Tenants

### ISSUE THREAD

**Issue by feorlen** [minio/docs#1046]
The current Helm deploy page only covers a new Operator deployment, not upgrading one that was previously installed with Helm. 

@cniackz has notes on 5.0.9->5.0.10 that can be applied to other versions. (I believe most recent ones are covered by these steps.
https://github.com/minio/wiki/wiki/Helm-Upgrade-5.0.9-to-5.0.10

**Comment by ravindk89** [comment]
We'll also need the "If you are using Helm to do installs, use Helm to do upgrades" as there are issues if you use `kubectl minio upgrade` or whatever the correct command is.

**Comment by cniackz** [comment]
Yes, the thing is, if we use helm to install things, we should use it for the upgrade as well.
Thank you, this issue looks good to me as a nice to have in the official docs.

**Comment by ravindk89** [comment]
Should close as part of #1021
