### ISSUE TITLE
Error in documentation: mc cp 

### ISSUE THREAD

**Issue by zveinn** [minio/docs#1050]
I'm pretty sure the example there is wrong, it's trying to copy two source objects into a single object and not a directory. 
We should probably remove the last "object.txt" part.
```
mc cp ~/data/object.txt myminio/mydata/object.txt play/mydata
```

# Link 
https://min.io/docs/minio/linux/reference/minio-mc/mc-cp.html
![image](https://github.com/minio/docs/assets/20964930/6f4d419c-7992-4490-979a-9740145cc180)

**Comment by ravindk89** [comment]
https://github.com/minio/docs/commit/6763b86c3cc995b5d2d996735d22a5fb1fe470d5

**Comment by ravindk89** [comment]
Thanks for catching this @zveinn !
