### ISSUE TITLE
[BUG] mc share upload page refers to downloading

### ISSUE THREAD

**Issue by wdinyes** [minio/docs#1085]
**Describe the bug**
On the "mc share upload" page, there are a couple of sections that refer to downloading, which I think is incorrect.

**To Reproduce**
1. Go to '[mc share upload](https://min.io/docs/minio/linux/reference/minio-mc/mc-share-upload.html)' page
2. In the first section, two items appear to be incorrect (there may be more):
"The [mc share upload](https://min.io/docs/minio/linux/reference/minio-mc/mc-share-upload.html#command-mc.share.upload) command generates a temporary presigned URL with integrated access credentials for **downloading** objects from a MinIO bucket."
and
"Applications can perform a PUT to **retrieve** the object from the URL."

(Emphasis added for emphasis.)

**Expected behavior**
Well, I mean, it should be upload access to the bucket.

**Additional context**
Oddly discovered this via some AI training.

**Comment by ravindk89** [comment]
dfa398f674bbb58c02c232ba68b62f03977c7cdb

**Comment by ravindk89** [comment]
SHould update within the next 10 minutes. Thanks for catching this @wdinyes !
