### ISSUE TITLE
Healthcheck documentation fails to mention that healthchecks are uncallable if User-Agent string contains "Mozilla" and "MINIO_BROWSER_REDIRECT" environment variable is not set to False

### ISSUE THREAD

**Issue by bdrans** [minio/docs#1086]
When MINIO_BROWSER_REDIRECT is not set, or has been explicitly set to `true`, MinIO has middleware which will detect if the User Agent string contains the sub-string `Mozilla`. If it does detect the sub-string, MinIO will redirect the request to the Admin Console. This includes all healthcheck endpoints so all healthchecks will result in a 307 response, and if the redirect is followed always result in a 200 because the login screen returns a 200.

The documentation uses curl as an example on how to call the endpoints, and will not run into the issue as curl sets the User Agent string to `curl/[version]` (see: https://everything.curl.dev/http/requests/user-agent). However if trying the equivalent commands in PowerShell (including the curl alias in PowerShell) you will run into the redirect as the default User-Agent string for PowerShell contains `Mozilla` (see https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.4#-useragent)

This can be demonstrated using the cluster maintenance check on single node cluster (as it should always fail) and calling the following and noting the return code is 307 as opposed to 412:
`Invoke-WebRequest -Uri https://minio:9000/minio/health/cluster?maintenance=true -MaximumRedirection 0`

Without the `-MaximumRedirection` parameter you follow the redirect and get a 200 response instead of the 412:
`Invoke-WebRequest -Uri https://minio:9000/minio/health/cluster?maintenance=true`

Getting the proper return code may be accomplished by setting `-UserAgent` to `""`:
`Invoke-WebRequest -Uri https://minio:9000/minio/health/cluster?maintenance=true -UserAgent ""`

**Comment by harshavardhana** [comment]
Which tool sets Mozilla user-agent that performs healthchecks?

**Comment by bdrans** [comment]
Yeah, I noticed that much of the documentation is more of a Linux focus even if on the Windows section of the docs site. I can definitely understand why the behavior is there, and I believe the behavior itself is the correct choice, but not realizing that behavior existed reading the Healthcheck API and trying to follow it on a Windows machine did leave me with some head scratching because it isn't mentioned in this portion of the docs. Only mention I could find is in the settings for the console (https://min.io/docs/minio/linux/reference/minio-server/settings/console.html#browser-redirect) but even then it doesn't mention the part of searching for the Mozilla keyword, for that you need to check the code: https://github.com/minio/minio/blob/4a21dce2b5537e3d2b8840427b6139a8282cad9e/cmd/generic-handlers.go#L146

**Comment by ravindk89** [comment]
Indeed - this is just an honest case of "ooh hey yeah windows does things different sometimes."

We'll add it to our todo list. Thanks for raising!
