### ISSUE TITLE
minio-go will need a documentation update once this PR is merged

### ISSUE THREAD

**Issue by zveinn** [minio/docs#1101]
Here is the PR: https://github.com/minio/minio-go/pull/1921
The new API is ( GetObjectAttributes )

**Comment by ravindk89** [comment]
cc @feorlen 

@zveinn https://github.com/minio/minio-go/blob/master/docs/API.md <- we pull this down and import it into our docs. So as long as the new API is in that markdown and documented, it happens automagically.

**Comment by feorlen** [comment]
To expand on the above: a new release in the relevant repo triggers the automagical docs update.

**Comment by zveinn** [comment]
Roger, so it's up to me to update the readme ?

**Comment by ravindk89** [comment]
Yes please - thus far at least the SDK maintainers tend to handle that side of the reference docs, at least for now.

**Comment by zveinn** [comment]
Will do!
