### ISSUE TITLE
Document additional limitations/lack thereof for attaching policies

### ISSUE THREAD

**Issue by feorlen** [minio/docs#1134]
[This access management page](https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#policy-document-structure) notes that JSON policies are limited to 2048 characters. 

It should note that there is no limit to the number of policies you may attach to a user or group. Investigate if there are other concerns about attaching a large number of policies (performance?) and include that information as well.

**Comment by ravindk89** [comment]
https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-policy-create.html#mc.admin.policy.create.POLICYPATH

**Comment by ravindk89** [comment]
as per engineering:

> There's a mistake in the documentation. The policy document size limit is 20KiB

**Comment by feorlen** [comment]
Also you can't have more than 10 tags. Not directly related to policies, but can be rolled into this change in some appropriate location.
