### ISSUE TITLE
Document pool management in Operator Console

### ISSUE THREAD

**Issue by feorlen** [minio/docs#1174]
Document how to create and manage pools using Operator Console. [There is a mention of it](https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant.html#deploy-and-view-the-tenant) but not yet detail about how to do it from the UI.

See related bug fix https://github.com/minio/operator/pull/1953 from release Operator v5.0.12 
Operator release docs issue: https://github.com/minio/docs/issues/1129

**Comment by ravindk89** [comment]
https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/expand-minio-tenant.html <- nothing here on pool expansion at all

**Comment by djwfyi** [comment]
Operator UI has been deprecated and removed as of 6.0.0.
