### ISSUE TITLE
S3 API Support Matrix

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#1178]
**Summary**

We have an internal ask to formally document the list of supported S3 APIs.

**Goals**

- [ ] Walk the list of S3 APIs present in https://github.com/minio/minio/blob/master/cmd/api-router.go
- [ ] Document the list at a high level (tabular format)
- [ ] Link (where possible) to the equivalent S3 API

**Non-Goals**

- Documenting the actual API request/response
- Documenting any MinIO Admin APIs
- Documenting the usage of the API

**Comment by ravindk89** [comment]
Handful of things I noticed

Notes:

- No `MethodPut` or `MethodDelete` for `torrent` object API
- No `MethodDelete` for ACL Object API

- Missing `MethodList` for Bucket Inventory
- Missing `MethodGet` for BucketCors
- Missing `MethodList` for BucketMetricsConfiguration
- Missing `MethodGet`, `MethodDelete`, `MethodList` for `BucketWebsite`
- No `MethodDelete` for BucketACL
- Missing `MethodList` for `intelligent-tiering`
- Missing `WriteGetObjectResponse`
- Missing `CreateSession`

**Comment by harshavardhana** [comment]
> Missing WriteGetObjectResponse

This isn't necessarily S3 not directly called. It's called via lambda functions we have a different functionality for this.
