### ISSUE TITLE
Emphasize that users should not modify data files directly

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#1186]
**Summary**

We need to explicitly state, likely in multiple places, that users should not manually modify, delete, or move around MinIO data files in any fashion - except where directed to by MinIO Engineering.

We have seen a few cases of users attempting to use various scripting / utilities to 'move' data from one node/drive to another.

These kinds of operations are trivially easy to do incorrectly and result in widespread corruption of data beyond MinIO's ability to heal.

**Goals**

List the in-scope goals

- [x] Add admonition to all installation docs related to exclusive data access to MinIO data
- [x] Add note to erasure coding docs to emphasize that users should not mutate shard/meta data
- [x] Add note to glossary to emphasize that users should not mutate shard/meta data
- [x] Add note to hardware checklist - storage emphasizing exclusive access to MinIO data
- [x] Add note to recovery docs to emphasize avoiding scripts/utilities for manually moving data around (e.g. cp, mv, rsync, etc.)

**Non-Goals**

A longer or deeper dive into shard behavior / data handling / healing

**Additional context**

We might have had some level of warning previously, but we unfortunately need to add and emphasize it due to incidents of severe user error.

**Comment by harshavardhana** [comment]
In fact, if they touch backend data without explicit guidance from MinIO engineers, it should be considered out of support.
