### ISSUE TITLE
Document readiness endpoint

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#1188]
**Summary**

We need to document both `mc ready` and its corresponding API endpoint `/minio/health/ready`

**Goals**

List the in-scope goals

- [x] Document the new APIs
- [x] Clarify their usage vs the existing health/liveness endpoints
- [x] Figure out when they were added (Optional)

**Comment by djwfyi** [comment]
`mc ready` was added in this PR from July 2022.
https://github.com/minio/mc/pull/4101

Which was included in [mc RELEASE.2022-07-06T14-54-36Z](https://github.com/minio/mc/tree/RELEASE.2022-07-06T14-54-36Z).

**Comment by djwfyi** [comment]
Readiness API is already documented at https://min.io/docs/minio/linux/operations/monitoring/healthcheck-probe.html.
Not adding the normal version add reference, as the command has been in for just about two years at this point.
