### ISSUE TITLE
Replace Operator plugin deploy instructions with Kustomize

### ISSUE THREAD

**Issue by feorlen** [minio/docs#1213]
Operator install using the plugin is deprecated as of v5.0.15. Replace the plugin instructions with the Kustomize ones instead.
Part 2 of https://github.com/minio/docs/pull/1202

Staged

Partially addresses https://github.com/minio/docs/issues/1210

**Comment by ravindk89** [comment]
:thinking: I feel we should just drop the plugin instructions wholesale. Kustomize has been around for the 5.0.x series for a while, so there's no reason to continue highlighting it as an option for previous versions within the current supported series.

**Comment by feorlen** [comment]
> 🤔 I feel we should just drop the plugin instructions wholesale. Kustomize has been around for the 5.0.x series for a while, so there's no reason to continue highlighting it as an option for previous versions within the current supported series.

The plugin still exists, but if we are ok with that then this is much easier.

**Comment by feorlen** [comment]
Docs consensus is nuke the plugin instructions ✅

**Comment by ramondeklein** [comment]
Not sure if it's already known, but I noticed that the plug-in instructions were already removed from the page (https://operator.min.io/), but not from the Table of Contents:
![image](https://github.com/minio/docs/assets/6048186/bc75e154-7493-460e-86fa-f0b9860ba88f)
