### ISSUE TITLE
Describe MinIO behavior with regards to multi-part uploads

### ISSUE THREAD

**Issue by ramondeklein** [minio/docs#1216]
MinIO behavior with regards to multi-part uploads deviates from AWS S3 in the following ways:
- MinIO doesn't allow listing all current multi-part uploads in a bucket.
- MinIO automatically purges non-aborted multi-part uploads after 24 hours.

Issues https://github.com/minio/minio/issues/5613, https://github.com/minio/minio/issues/11686 and https://github.com/minio/minio/issues/13246 proof that `ListMultipartUploads` can only be used to list multi-part uploads if an exact object-name is specified as a prefix.

Issue https://github.com/minio/minio/issues/16120 confirms that `AbortIncompleteMultipartUpload` is not supported when using `PutBucketLifecycle`. It looks like we're scanning every 6 hours and purge non-aborted multi-part uploads after 24 hours (see `stale_uploads_expiry` and `stale_uploads_cleanup_interval` in the [docs](https://github.com/minio/minio/tree/master/docs/config)). This behavior affects all APIs that deal with aborting incomplete multipart uploads lifecycle rules.

I think we should mark the APIs in the S3 API compatibility document that have restrictions and/or deviate from the standard AWS S3 APIs and provide a proper explanation why we deviate.

**Comment by feorlen** [comment]
We can expand the compatibility page to add this type of information. In the process, it would be nice to move the small section on unsupported endpoints from the [thresholds and limits page](https://min.io/docs/minio/linux/operations/concepts/thresholds.html) to the compatibility page.

**Comment by djwfyi** [comment]
> We can expand the compatibility page to add this type of information. In the process, it would be nice to move the small section on unsupported APIs from the [thresholds and limits page](https://min.io/docs/minio/linux/operations/concepts/thresholds.html) to the compatibility page.

All of the APIs referenced on the thresholds and limits page are already listed in the unsupported API bucket endpoint list.
Maybe a link between the two pages? Or just delete the section on the limits page?

**Comment by ramondeklein** [comment]
@djwfyi The `ListMultipartUploads` limitations are not described on that page.

**Comment by djwfyi** [comment]
> [@djwfyi](https://github.com/djwfyi) The `ListMultipartUploads` limitations are not described on that page.

@ramondeklein Right. I was commenting on @feorlen's suggestion of expanding the scope of the request.

I do fear that this is a rabbit hole we don't have enough bandwidth or insight to address at the moment, but I agree that it is a good request. Just if we do it for multipart, we should expand all of them.
