### ISSUE TITLE
KES menu items refer to invalid URLs

### ISSUE THREAD

**Issue by ramondeklein** [minio/docs#1227]
Subitems under **Product** and **Solutions** from https://min.io/docs/kes link to non-existing URLs:

![image](https://github.com/minio/docs/assets/6048186/10af6337-00a6-445b-ad76-3745a0bf13d3)

**Comment by ravindk89** [comment]
@kaankabalak @rushenn it looks like the URLs are using min.io/docs/kes as the root instead of min.io - is this a change that has to happen in the docs-kes-theme repo?

**Comment by rushenn** [comment]
@ravindk89 Will send a PR shortly to fix the URLs

**Comment by rushenn** [comment]
@ravindk89 Please take a look https://github.com/minio/kes-docs-theme/pull/31
