### ISSUE TITLE
[BUG] Wrong links in container quickstart

### ISSUE THREAD

**Issue by matteocontrini** [minio/docs#1233]
**Describe the bug**
In the quick start container guide, the links to `Single-Node Single-Drive` and `Deploy MinIO: Multi-Node Multi-Drive` bring to the Linux version of those pages, instead of the containers version.

**To Reproduce**
1. Go to https://min.io/docs/minio/container/index.html
2. Click on the two links mentiond above in the "Quickstart for Containers" chapter
3. See that the destination URLs are:

- `https://min.io/docs/minio/linux/operations/installation.html#minio-installation-comparison`
- `https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html#deploy-minio-distributed`

**Expected behavior**
The links should probably be:

- `https://min.io/docs/minio/container/operations/installation.html`
- `https://min.io/docs/minio/container/operations/install-deploy-manage/deploy-minio-single-node-multi-drive.html`

Notice the `container` instead of `linux` in the URL.

**Comment by feorlen** [comment]
Hi @matteocontrini, thank you for the issue and welcome to the MinIO docs repo 😄 

In this case, the page is functioning as intended. Those links do go to "Linux versions," as not all pages have a version for every platform. In this case they were intended as general information relevant to multiple platforms.

We are in the process of restructuring the documentation for the different platforms, I will add your feedback to our task for this. It should be clear when something is relevant to a specific platform or when it is applicable to several platforms.
