### ISSUE TITLE
[BUG] `mc batch` incorrect command examples 

### ISSUE THREAD

**Issue by ramondeklein** [minio/docs#1235]
The `mc batch generate` and `mc batch start` commands show the following syntax:
```
mc [GLOBALFLAGS] batch generate \
                       TARGET   \
                       JOBTYPE
```
where `TARGET` is described as "_The [alias](https://min.io/docs/minio/linux/reference/minio-mc/mc-alias-set.html#alias) used to generate the YAML template file. The specified alias does not restrict the deployment(s) where you can use the generated file._". Although the syntax specifies the `TARGET`, all examples use `mc batch generate myminio/mybucket replicate`.

Although it works with specifying a bucket, the bucket-name is ignored and it would be better to leave them out, so:
```
mc batch start myminio/mybucket jobfile.yaml
```
should be:
```
mc batch start myminio jobfile.yaml
```

and
```
mc batch replicate myminio/mybucket replicate
```
should be:
```
mc batch replicate myminio replicate
```

**Comment by djwfyi** [comment]
This is a good catch. Fixing.
