### ISSUE TITLE
[BUG] Server-Side Encryption with Client-Managed Keys example uses deprecated flag

### ISSUE THREAD

**Issue by LenzGr** [minio/docs#1259]
**Describe the bug**
The documentation [Server-Side Encryption with Client-Managed Keys (SSE-C)](https://min.io/docs/minio/container/administration/server-side-encryption/server-side-encryption-sse-c.html) provides CLI examples that use the `--encrypt-key` flag, which seems to be deprecated.

Running the command with this option returns an error:
```
mc: <ERROR> a deprecated Flag: '--encrypt-key' has been deprecated, please use --enc-c instead.
```

**To Reproduce**
1. Try running the examples in this chapter
2. Observe the error message

**Expected behavior**
The examples should be updated to use the new `--enc-c` flag instead.

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Version: mc installed via HomeBrew
```
mc version RELEASE.2024-06-29T19-08-46Z (commit-id=f5b325d9d399e09b4d21384081e397a52f6ca89d)
Runtime: go1.22.4 darwin/arm64
Copyright (c) 2015-0000 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

**Comment by feorlen** [comment]
Hi @LenzGr thanks for the docs bug! 🐛 

We have an open issue for this as part of related docs changes for https://github.com/minio/docs/issues/1191. You may wish to follow that issue for updates.
