### ISSUE TITLE
Add example ILM rule to remove delete markers

### ISSUE THREAD

**Issue by feorlen** [minio/docs#1262]
I don't think we have this exact example anywhere in the web docs. @allanrogerr has kindly repaired the one in the GitHub docs so now it works. See https://github.com/minio/minio/pull/20056

Some likely destinations for such an example:
* https://min.io/docs/minio/linux/administration/object-management/object-delete.html#lifecycle-management-expiration
* https://min.io/docs/minio/linux/administration/object-management/create-lifecycle-management-expiration-rule.html#minio-lifecycle-management-create-expiry-rule

**Comment by ravindk89** [comment]
Unless we have a significant amount of community/customer requests for documenting the JSON rule creation approach I think we are OK focusing on the mc ilm rule route
