### ISSUE TITLE
Document CONSOLE_SUBPATH

### ISSUE THREAD

**Issue by feorlen** [minio/docs#1264]
Running the MinIO Console on a subpath may require setting `CONSOLE_SUBPATH`, which isn't documented.

Additional information from @ramondeklein:
> I tried to run the console on a sub-path (`/minio/ui`) and it didn't work because the HTML contains `<base href="/" />`. After some digging in the code I found that I needed to set `CONSOLE_SUBPATH`

> If you run the MinIO console as a standalone service, then you need to set `CONSOLE_SUBPATH`. If you run console integrated in normal MinIO service (using `--console-address`), then you need to set `MINIO_BROWSER_REDIRECT_URL`. MinIO takes care of setting `CONSOLE_SUBPATH` in that scenario.

Also follow up with eng to see if there is the intention to simplify these two seemingly independent methods.

**Comment by ramondeklein** [comment]
I don't think we need to document running MinIO and the Console as separate executables. `MINIO_BROWSER_REDIRECT_URL` is documented, so this issue can be closed.

**Comment by feorlen** [comment]
I'll discuss with docs team if we should document the envvar alone, without a comprehensive discussion on actually setting up this arrangement. Seems it comes up from time to time and not documented in GitHub .md docs either.
