### ISSUE TITLE
[BUG] Fix `curl` command in Splunk blog item

### ISSUE THREAD

**Issue by ramondeklein** [minio/docs#1265]
The blog on https://blog.min.io/minio-notifications-in-splunk shows the following command:
![image](https://github.com/minio/docs/assets/6048186/36032c15-90b9-489b-bd66-ac9233e97700)
It should be `http:` (with a colon). Please also use normal text, so users can copy the command.

**Comment by feorlen** [comment]
@aj-jester is fixing 🥇

**Comment by feorlen** [comment]
@aj-jester replaced this example with a corrected text version. Thanks!

Perhaps someone will do an updated blog post in the future, but not right now.
