### ISSUE TITLE
Document support for metrics-v3 api in `mc admin prometheus metrics|generate`

### ISSUE THREAD

**Issue by anjalshireesh** [minio/docs#1266]
ref: 

https://github.com/minio/mc/pull/4982
https://github.com/minio/mc/pull/4985

**Comment by feorlen** [comment]
@anjalshireesh thanks for the issue 🎉  when do you expect v3 metrics will be in a release? I presume the next one? So we can note when this was added.

**Comment by anjalshireesh** [comment]
> @anjalshireesh thanks for the issue 🎉 when do you expect v3 metrics will be in a release? I presume the next one? So we can note when this was added.

@feorlen yes, now that both the PRs have been merged, the next `mc` release will contain the v3 api support in `mc`.

**Comment by feorlen** [comment]
See also https://github.com/minio/minio/pull/20090

**Comment by djwfyi** [comment]
Changes included in mc [RELEASE.2024-07-11T18-01-28Z](https://github.com/minio/mc/releases/tag/RELEASE.2024-07-11T18-01-28Z).
