### ISSUE TITLE
[BUG] The Operator Console is still mentioned in the Operator installation output

### ISSUE THREAD

**Issue by pavelanni** [minio/docs#1291]
**Describe the bug**

The command output in pp. 1, 2, and 3 in this section https://min.io/docs/minio/kubernetes/upstream/operations/installation.html#install-the-minio-operator-using-kustomize still mentions the Console pods, secrets, and deployments.

Most importantly, in the `2. Verify the Operator pods are running` it shows three pods: two `operator` ones and one `console`. As of v6.0, the Console is not installed so it will confuse the users. They won't see the Console pod and decide that the installation failed.

**Comment by ravindk89** [comment]
Good catch - I did a pass for the helm instructions but missed the Kustomize ones.

I'm going to drop the output list of CRD things - that can change between releases and it's not realistic for us to maintain it.
