### ISSUE TITLE
Clarify permissions required for `mc admin update`

### ISSUE THREAD

**Issue by feorlen** [minio/docs#1301]
On the [`mc admin update`](https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-update.html) reference page, this paragraph says the command may require sudo:
```
After running the command, a prompt displays to confirm the update.
Type ``y`` and ``[ENTER]`` to confirm and proceed with the update.
You may need to use ``sudo`` if your user does not have write permissions for the path where ``mc`` is installed.
```

`mc admin update` itself doesn't inherently require sudo. But the target location for the binary needs to be writable by the user executing the command. The user must be able to write to the path to stage a copy of the new binary before replacing the existing one. 

Presumably humans aren't logging in as the user that runs the `minio` process or owns the install location. Maybe make it writable for an appropriate group? We should clarify with engineering what makes sense to recommend here. 

`includes/linux/steps-upgrade-minio-deployment.rst` mentions the user running the `minio` process needs r/w on the binary, which isn't the same thing. Might be a good place to clarify, along with other text that references (or should reference) upgrading.

Related:
`includes/minio-server-installation.rst` mentions `mc admin update` (about source-based installations) but this include appears to not be used anywhere.

**Comment by djwfyi** [comment]
We don't want to tell people to be using `sudo`.
