### ISSUE TITLE
[BUG] Documentation URL for Amazon s3 incorrect in Linux reference

### ISSUE THREAD

**Issue by pixarbuff** [minio/docs#1311]
**Describe the bug**
on https://min.io/docs/minio/linux/reference/minio-mc.html the URL for S3 is incorrect; it should be https://s3.amazonaws.com

**To Reproduce**
$ mc alias set myAlias https://s3.amazon.com ACCESS_KEY SECRET_KEY
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "https://s3.amazon.com": dial tcp 72.21.210.29:443: connect: connection refused.
**Expected behavior**
Changing the URL to amazonaws.com fixes it:
$ mc alias set myAlias https://s3.amazonaws.com ACCESS_KEY SECRET_KEY
Added `myAlias` successfully.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**

**Comment by djwfyi** [comment]
```
{your-amazon-instance-URL}
```

See: https://docs.aws.amazon.com/general/latest/gr/s3.html

**Comment by pixarbuff** [comment]
@djwfyi none of the examples in the URL you provided have either the minio documented url or my corrected url; can you describe what the link is for? Also, "{your-amazon-instance-URL}" is not in the documentation either; can you describe what you wrote that for?

**Comment by djwfyi** [comment]
> @djwfyi none of the examples in the URL you provided have either the minio documented url or my corrected url; can you describe what the link is for? Also, "{your-amazon-instance-URL}" is not in the documentation either; can you describe what you wrote that for?

The URL in the example is just a dummy URL. It was never intended to be copy and pasted as is and used. You need to replace it with the URL to your s3 instance. There is no one filler URL that will work for all S3 users. So the proposal is to replace the URL in the example with something like what I noted above instead of anything that looks like it could be copy/pasted as is.

**Comment by pixarbuff** [comment]
Thanks for the clarification. All the URLs follow the same pattern:
`s3.us-east-2.amazonaws.com`
so maybe change the documentation to
`s3.{your-region}.amazonaws.com`
