### ISSUE TITLE
[BUG] Enhance "Root Access Settings"  to mention even with KES that the MINIO_ROOT_USER and MINIO_ROOT_PASSWORD are still required

### ISSUE THREAD

**Issue by ocient-jlarson** [minio/docs#1325]
**Describe the bug**

[https://min.io/docs/minio/linux/reference/minio-server/settings/root-credentials.html](url)

The follow doc makes it seem that the fields `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` are no longer required in the `/etc/default/minio` if KES is being leveraged to create a key upon startup.

While the key does exist within Hashi Vault (for this example) - commenting these `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` settings result in nodes being unable to properly startup and communicate with each other.

Even with KES using external systems, these are still required settings. It is easy to infer from the doc that you can rid the file of these passwords.

**Comment by feorlen** [comment]
Thanks for the docs bug @ocient-jlarson !
