### ISSUE TITLE
[BUG] The page "Deploy MinIO: Single-Node Single-Drive" for Linux actually describes single-node multi-drive deployment

### ISSUE THREAD

**Issue by dhananjaykrutika** [minio/docs#1330]
**Describe the bug**

The documentation for deploying single-node single-drive server on Linux actually lists down instructions for deploying a single-node multi-drive instance.

**To Reproduce**
1. Go to https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html#
2. The instructions create 4 drives /mnt/disk{1..4} that serve as storage for the minio server.
3. And these instructions are not very different from those for deploying SNMD in Linux -- https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-multi-drive.html

**Expected behavior**
The instructions laid out for the MacOS documentation seem more accurate -- https://min.io/docs/minio/macos/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html. This is what the SNSD page for Linux should also be showing.

**Screenshots**
See links above.

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by ravindk89** [comment]
The actual env file is correct, but this is likely an include that needs cleaning up.

@Bradamant3 this might be another good 'first issue' sort of thing for getting your feet wet in our Sphinx build.
