### ISSUE TITLE
[BUG] LDAP distinguished names need to be semicolon separated

### ISSUE THREAD

**Issue by feorlen** [minio/docs#1341]
This section about the `MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN` envvar says the search base DNs are comma separated. Apparently they should be semicolon separated? Should investigate if there are other affected LDAP configs, such as `MINIO_IDENTITY_LDAP_USER_DN_ATTRIBUTES` and related configuration settings.

https://min.io/docs/minio/linux/reference/minio-server/settings/iam/ldap.html#envvar.MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN

cc @vadmeste, further clarification appreciated

**Comment by ravindk89** [comment]
https://github.com/minio/pkg/blob/main/ldap/ldap.go

```
const (
	dnDelimiter   = ";"
	attrDelimiter = ","
)

```

**Comment by ravindk89** [comment]
@donatello @vadmeste I think `attributes` are always derived, so really we need to just specify that for the group and search base DNs, its `;` for delimiter right?

**Comment by djwfyi** [comment]
As a Distinguished Name is itself a comma-separated list of attribute=value pairs, multiple DNs have to be separated by a different character. Therefore, a `;` is required if providing multiple DNs.

Attributes are separated by commas.
