### ISSUE TITLE
[BUG] Options objects are not documented in website

### ISSUE THREAD

**Issue by Its-Alex** [minio/docs#1352]
**Describe the bug**
Hello :wave:,
Is it possible to document the content of opts in function?

**To Reproduce**
1. Go to https://min.io/docs/minio/linux/developers/javascript/API.html#removeobject-bucketname-objectname-removeopts
2. See `removeopts` that is not documented

**Expected behavior**
This would be awesome to document each time there is a opts object in a function.

**Screenshots**
![image](https://github.com/user-attachments/assets/58ba2a70-4183-4d52-8a0d-9666767c6eae)

**Comment by ravindk89** [comment]
We pull that down directly from https://github.com/minio/minio-js/blob/master/docs/API.md

So if it changes there, it changes in our docs at the next new commit. cc/ @prakashsvmx 

https://github.com/minio/minio-js/blob/master/src/internal/client.ts#L1168-L1197

https://github.com/minio/minio-js/blob/master/src/internal/client.ts#L183

Looks like it's just three possible things:

`versionId`
`governanceBypass`
`forceDelete`

**Comment by Its-Alex** [comment]
@ravindk89 

> We pull that down directly from https://github.com/minio/minio-js/blob/master/docs/API.md

Thanks I will open a PR there :+1: 

> Looks like it's just three possible things:

I found it in the code but that would be so much nice if it was directly in the documentation
