### ISSUE TITLE
[BUG] Double icons on this page, maybe more

### ISSUE THREAD

**Issue by marktheunissen** [minio/docs#1376]
**Describe the bug**

OS Icons are doubled

**To Reproduce**

https://min.io/docs/minio/container/operations/checklists/thresholds.html

**Expected behavior**

Single icons

**Screenshots**

<img width="736" alt="Screenshot 2024-11-28 at 10 56 40" src="https://github.com/user-attachments/assets/c813eafc-6692-43ac-96d4-4a8a7bc792e7">

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrome 
 - Version Version 131.0.6778.86 (Official Build) (arm64)

**Comment by rushenn** [comment]
Something seems off with this page. The markup for the double icon on [thresholds.html](https://min.io/docs/minio/container/operations/checklists/thresholds.html) doesn't appear to exist in the source code. When I build the site locally, I don’t see that page either.

Interestingly, navigating to other pages within the same menu group (e.g., hardware.html or software.html) causes [Thresholds and Limits](https://min.io/docs/minio/container/operations/checklists/thresholds.html#) to disappear entirely from the menu. This particular page displays the old top navigation, which no longer exists.

Could this issue be related to hosting, similar to the one we faced during the website launch? @djwfyi @ravindk89

**Comment by ravindk89** [comment]
This might be a hosting issue, or we may need to redeploy the docs overall.

@donatello did we fix up the auto-build script already?

**Comment by djwfyi** [comment]
This goes to a 404 now.
https://github.com/minio/docs/pull/1020 moved the page from /checklists/thresholds.html to `/concepts/thresholds.html`.

Not sure how that page even showed up in the Container pages.

**Comment by ravindk89** [comment]
I think while we were fixing things one or more broken builds got pulled in by the autobuilder, and then everything stopped working so we had a half-built state.

Once we finalize the redirect project we will be deprecating those other pages anyways, which will also help

**Comment by marktheunissen** [comment]
Yep looks good now, there are no icons. Thanks
