### ISSUE TITLE
[BUG] DISABLE_PAGER without MC_ prefix

### ISSUE THREAD

**Issue by c33s** [minio/docs#1377]
**Describe the bug**

the [mino client settigs page][1] shows `DISABLE_PAGER` without `MC_` prefix as env var name to disable the pager. without the `MC_` it does't disable the pager. 

```
cli version RELEASE.2024-05-24T09-08-49Z (commit-id=0000000000000000000000000000000000000000)
Runtime: go1.22.5 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```
packaged version of alpine  3.20 made me notice it as `mc ls --help` shows a progress bar stuck as 0%. quite akward that the progress bar is used as pager. can only exit it by pressing `q`

setting `MC_DISABLE_PAGER=true` fixes the pager for me. should be fixed in the docs.

[1]: https://min.io/docs/minio/linux/reference/minio-mc/minio-client-settings.html

**Comment by ravindk89** [comment]
https://github.com/minio/mc/blob/1681e4497c09d7438a34e846f76dbde972ab7daf/cmd/globals.go#L99

https://github.com/minio/mc/blob/1681e4497c09d7438a34e846f76dbde972ab7daf/cmd/flags.go#L49

Bingo. Yep needs a prefix.
