### ISSUE TITLE
Virtual-host-style requests by default in Cyberduck

### ISSUE THREAD

**Issue by dkocher** [minio/docs#280]
Cyberduck 7.2 and Mountain Duck 3.3 or later use virtual-host-style requests for third party S3 providers by default. Please adjust the documentation accordingly that users must make sure to enable ​virtual-host-style requests in their Minio configuration.

**Comment by harshavardhana** [comment]
Feel free to send a PR @dkocher

**Comment by Evsio0n** [comment]
HI, Seems I got this issue when I am using CyberDuck with minio, error encountered as Failed to parse XML document with handler class org.jets3t.service.impl.rest.XmlResponsesSaxParser$ListBucketHandler.

Minio Config within `/etc/default/minio`:

```
MINIO_REGION_NAME="HK1"
MINIO_BROWSER_REDIRECT_URL="https://s3-console.nexet.hk"
#MINIO_SERVER_URL="https://s3.nexet.hk"

```


<img width="862" alt="截屏2022-05-09 01 53 30" src="https://user-images.githubusercontent.com/29672485/167308971-50d09b7d-83de-4bc2-8fcb-4fce75a4348c.png">
