### ISSUE TITLE
iOS example is out date and using deprecated methods

### ISSUE THREAD

**Issue by gossmer** [minio/docs#289]
The API's shown in the example for the swift iOS cookbook (AWSS3TransferManager.s3TransferManager) have been deprecated by the AWS S3 framework. The replacement methods (AWSS3TransferUtility.s3TransferUtility) don't work because of some checksum issues on minio. Seems similar to a bug fixed years ago ( https://github.com/minio/minio/issues/5298) 

If Amazon removes the deprecated methods minio will not be supported for iOS.

**Comment by harshavardhana** [comment]
@gossmer please update them

**Comment by gossmer** [comment]
The method replacement calls are pretty simple but the problem is the interaction with Minio and why it rejects the upload/download (based on headers?). I don't know enough about the minio code to know why it fails.

**Comment by vasyares** [comment]
I am sorry but will we be lucky to see any updates in the nearest future?

**Comment by harshavardhana** [comment]
> I am sorry but will we be lucky to see any updates in the nearest future?

Feel free to send a PR to update the examples @vasyares  - happy to accept any PR

**Comment by gossmer** [comment]
I would be glad to update the iOS samples but this is not an iOS issue. There is something in the checksum on the minio side that rejects it. Not sure why this issue should be closed since it is not solved.

**Comment by harshavardhana** [comment]
> I would be glad to update the iOS samples but this is not an iOS issue. There is something in the checksum on the minio side that rejects it. Not sure why this issue should be closed since it is not solved.

Feel free to provide a reproducer, and open relevant issue in minio/minio this is a documentation site.
