### ISSUE TITLE
Update the Caddy configuration for Caddy v2

### ISSUE THREAD

**Issue by cboettig** [minio/docs#291]
[Caddy configuration page](https://docs.min.io/docs/setup-caddy-proxy-with-minio.html) looks like it is currently for Caddy v1, which "will go away soon" https://caddyserver.com/v1/.  These docs should be updated for Caddy v2, https://caddyserver.com/docs/v2-upgrade. The docs should also explicitly note the Caddy version.

**Comment by harshavardhana** [comment]
Feel free to update the docs @cboettig happy to accept any PR
