### ISSUE TITLE
"Distributed minio on docker swarm" docs have mulltiple errors

### ISSUE THREAD

**Issue by Sebi2020** [minio/docs#296]
I'm talking about the following page: https://docs.min.io/docs/deploy-minio-on-docker-swarm.html

The docs say:
> The docker-compose.yml file also exposes the MinIO services behind a single alias on the minio_distributed network.

and

> Services in the Swarm which are attached to that network **can interact with the host "minio-cluster" instead of individual services' hostnames**. This provides a simple way to loosely load balance across all the MinIO services in the Swarm as well as simplifies configuration and management.

The [docker-compose.yaml](https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-swarm/docker-compose-secrets.yaml) does not define an alias at all.

The **different** services (this are not load-balanced swarm service tasks) are not accessible by a common alias because the file does not define such a network alias.

> Docker Swarm uses ingress load balancing by default. [...]

This does apply only to service **tasks** but they are not used at all. The file defines 4 services which are bound to a specific node. Thereas the ingress network of docker does not play any role at all. (Each instance uses a different port and is constrained to one node).

**Comment by harshavardhana** [comment]
@Sebi2020 how about fixing the doc? happy to accept a PR.

**Comment by djwfyi** [comment]
This doc has been dropped, and we are not documenting Swarm going forward.
