### ISSUE TITLE
feature request: doc split-up

### ISSUE THREAD

**Issue by c33s** [minio/docs#313]
currently nearly every web search about the client leads to https://docs.min.io/docs/minio-client-complete-guide.html if the section would be split up with search engine friendly urls things would be easier to find

**Comment by ravindk89** [comment]
Hi @c33s , 

I'm currently working on a large-scale re-write of the documentation. You can take a look at the `master` branch to get an idea of the direction we're moving in. Moving forward, each `mc` and `mc admin` command will have its own dedicated URL, examples, etc. This should hopefully not only resolve your initial concern, but make it easier for users who are trying to easily reference the various command line tools.

As of such, improvements to the legacy docs are not a priority. I am hoping to have a replacement ready by end of year, or perhaps very early in 2021 depending on how quickly I can work.

I appreciate your patience in this regard.

**Comment by ravindk89** [comment]
hI @c33s  - https://docs.min.io/minio/baremetal/reference/minio-cli/minio-mc.html is now live. I think this resolves what you are looking for in terms of a more navigable `mc` reference.

**Comment by c33s** [comment]
really cool. thank you very much for your work. hopfully google will soon create a good index of the docs :)

feel free to close, i just let it open in case you want it to be open as long as the news docs are not on the production docs page.
