### ISSUE TITLE
wrong image in one-way server side bucket replication

### ISSUE THREAD

**Issue by mznet** [minio/docs#340]
While I looking into [Enable One-Way Server-Side Bucket replication doc](https://docs.min.io/minio/baremetal/replication/enable-server-side-one-way-bucket-replication.html), I found "active-active replication" image has been used in the doc. And [Two-way replication docs](https://docs.min.io/minio/baremetal/replication/enable-server-side-two-way-bucket-replication.html) has the same image, too. It's little bit confusing. As far as i know, one-way replication is not active-active, it's an active-passive. Therefore, Wouldn't it be better to used active-passive image for one-way replication doc?

![image](https://user-images.githubusercontent.com/9622730/115244840-4bc37d80-a15f-11eb-8cae-395df8768250.png)

**Comment by ravindk89** [comment]
Thanks for the heads up @mznet , I can have this fixed shortly.

**Comment by ravindk89** [comment]
https://github.com/minio/docs/commit/abc1e567fe1d3fb7f098a89916ffdf59eb8b6c4e

Rebuilding and publishing docs now. Should be fixed within a few minutes. Thanks again!
