### ISSUE TITLE
Bad environment variable. MINIO_STORAGE_CLASS_REDUCED should be MINIO_STORAGE_CLASS_RRS

### ISSUE THREAD

**Issue by washtubs** [minio/docs#345]
I just encountered this discrepancy here. https://docs.min.io/minio/baremetal/concepts/erasure-coding.html#bitrot-protection

Had to check the source to see which one was right.

**Comment by ravindk89** [comment]
https://docs.min.io/minio/baremetal/concepts/erasure-coding.html#storage-classes

Fixed in https://github.com/minio/docs/commit/b23cae7aed4767f43812c768da5e19103683bfbd - thanks for identifying this!
