### ISSUE TITLE
Optimize Bucket Notification ARN collection

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#346]
Per customer feedback, retrieving the [ARN](https://docs.min.io/minio/baremetal/monitoring/bucket-notifications/publish-events-to-kafka.html#restart-the-minio-deployment) can be difficult if the user does not have access to the subsequent console logs (permissions, access, etc.)

A more reliable method would be to use `mc admin info --json ALIAS` to retrieve the server configuration and parse the JSON for the required ARN. 

via @kannappanr the command `mc admin info ALIAS --json | jq .info.targetARN` should work, though it requires installing `jq`. `info` subs out for the acronym/short-name for each bucket notification target

# Goals

Update Bucket Notification target docs with alternative ARN retrieval instructions

# Non-Goals

Any other changes to bucket notification documentation.

**Comment by ravindk89** [comment]
This is a good starting issue. You'll need to add a section to the existing bucket notification tutorials where, instead of introspecting server logs and hoping to get lucky, the user can run the above.

You can test this against play.min.io - note that the jq path is now `.info.sqsARN` instead of `targetARN`

**Comment by djwfyi** [comment]
Correct the typo in the table heading label at 
https://docs.min.io/minio/baremetal/reference/minio-mc/mc-event-add.html#supported-bucket-events

![vlaue](https://user-images.githubusercontent.com/53910321/158706986-6d69d012-b64d-4358-9d5c-026df83cdd32.png)
