### ISSUE TITLE
Move TOC under main content and show sidebar toggle by default

### ISSUE THREAD

**Issue by rushenn** [minio/docs#364]
> The logic to move the TOC into the main content bar happens irrespective of screen size. In really basic testing, the page looks like junk for anything < the md breakpoint.

> Keep the sidebar toggle visible by default - That way users can prioritize screen reading width regardless of screen size. Right now the toggle only appears for smaller screen sizes.

**Comment by harshavardhana** [comment]
> https://miniohq.slack.com/archives/C013NDUJKMK/p1627054788180600

Private links @rushenn let's avoid them - publicly not readable. Lets paste the actual content here.
