### ISSUE TITLE
Add MINIO_PROMETHEUS_JOB_ID to Prometheus section

### ISSUE THREAD

**Issue by cb3inco** [minio/docs#366]
Under the following link - https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/collect-minio-metrics-using-prometheus.html

There is no documentation about including MINIO_PROMETHEUS_JOB_ID if you change the scrape job name from the default. This needs to be added.

**Comment by ravindk89** [comment]
This was fixed in https://github.com/minio/docs/commit/ab25dd2059d11a292185f012204da8f507d60e8c
