### ISSUE TITLE
GPG key information

### ISSUE THREAD

**Issue by psztoch** [minio/docs#382]
**Summary**

Please add information about GPG key used to sign release files, in example:
* https://dl.min.io/client/mc/release/linux-arm64/mc.RELEASE.2021-09-02T09-21-27Z.asc
* https://dl.min.io/server/minio/release/linux-amd64/minio.RELEASE.2021-09-09T21-37-07Z.asc

This key should be uploaded to https://dl.min.io and some information about signature verification should be added to documentation.

**Comment by harshavardhana** [comment]
GPG is legacy use minisign much better 

> minisign -VQm /opt/bin/minio -P RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav


Make sure to download https://dl.min.io/server/minio/release/linux-amd64/minio.minisig in the /opt/bin/minio.minisig

Infact this is already validated when you do `mc admin update` 

GPG is kept for legacy reasons and we have no plans to document it.
