### ISSUE TITLE
Synchronize Bucket Notification content and clean up tutorial

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#383]
**Summary**

[Bucket Notification Events](https://docs.min.io/minio/baremetal/monitoring/bucket-notifications/bucket-notifications.html#object-events) has fallen out of sync and needs to include the `s3:EVENT:*` type selectors as well

There's also confusion where `mc event add` and MinIO Console support a subset of multi-event selectors, but not granular event selection. 

**Goals**

- [x] Synchronize the list of bucket events with latest MinIO, include all multi-event selectors
- [x] Update `mc event` references to better explain the supported events
- [x] Update MinIO Console guide to better explain the supported events

**Non-Goals**

Updating the various bucket notification tutorials to include both SDK and CLI examples

**Additional context**

- [minio/mc/cmd/client-s3.go](https://github.com/minio/mc/blob/master/cmd/client-s3.go#L243-L276)
- [minio/minio/internal/event/name.go](https://github.com/minio/minio/blob/master/internal/event/name.go)

**Comment by djwfyi** [comment]
This ticket has been taken care of through other work somewhere along the way.
Verified that all tasks are complete in the current docs.
