### ISSUE TITLE
[FEATURE] Add example for aws-sdk-go-v2

### ISSUE THREAD

**Issue by rennnosuke** [minio/docs#406]
## Summary
The documentation for [aws-sdk-go](https://github.com/aws/aws-sdk-go) has already been added to this PR (https://github.com/minio/docs/pull/69) , but I can't find any documentation for [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2). So it's would be better to add it.

## Goals
- [ ] Add document how to use aws-sdk-for-go-v2 with MinIO server

## Additional Context
In this comment(https://github.com/minio/docs/pull/348#issuecomment-861063106),  the cookbook documentation is planed to deprecate. So I'm not sure if this document should be added as cookbook.

**Comment by ravindk89** [comment]
@rennnosuke At this time, adding docs for the AWS Go SDK would not be a priority.

We do have our own [Go SDK](https://docs.min.io/docs/golang-client-api-reference.html) which we intend to continue creating documentation for moving forward.

With regards to the linked comment, we need to revisit the Cookbook docs to be something more maintainable and useful in the long term, vs something that goes out of date and remains stale until someone has spare cycles to take a look. 

Looking at the [V2 Go Docs](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/) I would presume that overriding the S3 endpoint to point to MinIO should be a good starting point.

**Comment by ravindk89** [comment]
Closing this issue as we do not have the resources to address it anytime soon.

When we get to the point of being able to bring up a cookbook/devhub, requests like these will make sense to keep open.

**Comment by TheApeMachine** [comment]
Sorry, I know this is closed, but it took me a while and I think it is worth leaving the solution for people stumbling onto this.

```golang
resolver := aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
    return aws.Endpoint{
        PartitionID:       "aws",
        URL:               "http://127.0.0.1:9000",
        SigningRegion:     "us-east-2",
        HostnameImmutable: true,
    }, nil
})

conn := s3.NewFromConfig(aws.Config{
    Region:           "us-east-2",
    Credentials:      credentials.NewStaticCredentialsProvider("minioadmin", "minioadmin", ""),
    EndpointResolver: resolver,
}, func(o *s3.Options) {
    o.UsePathStyle = true
})
```
