### ISSUE TITLE
Audit Webhook: Update Auth_token documentation

### ISSUE THREAD

**Issue by mshanmu** [minio/docs#407]
https://docs.min.io/minio/baremetal/monitoring/logging/minio-logging.html#id2

When publishing audits through webhook, the above documentation mentions 

"Replace TOKEN with a JSON Web Token (JWT) to use for authenticating to the webhook endpoints. Omit for endpoints which do not require authentication."

This information is incorrect. 

Try doing "mc admin config set minio audit_webhook:elastic endpoint="<endpoint>" auth_token="<JWT token>". This will never work, every time failing with 401 error.

The reason is in, https://github.com/minio/minio/blob/master/internal/logger/target/http/http.go#L89 , it sets the Authorization header without "Bearer" keyword. I think this was a oversight.

But it is a good oversight :), thereby, allows the customer to set any type of authorization, which is very much desired, like below,

$ echo -n 'user:password' | base64
dXNlcjpwYXNzd29yZA==
$
$ mc admin config set minio audit_webhook:elastic endpoint="<endpoint>" auth_token="Basic dXNlcjpwYXNzd29yZA=="

I confirmed that this works well. 

Similarly, for JWT token, it will be like below,

$ mc admin config set minio audit_webhook:elastic endpoint="<endpoint>" auth_token="Bearer token"

Tried through the environment variables MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_<IDENTIFIER> and it did not work.

## Steps to Reproduce (for bugs)

1. Setup an audit webhook with auth token
2. Notice it does not work

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio/minio:RELEASE.2021-11-03T03-36-36Z

**Comment by harshavardhana** [comment]
> So specifically, `MINIO_LOGGER_WEBHOOK_AUTH_TOKEN` or its cmd analog `audit_webhook auth_token` supports specifying both Bearer tokens and plaintext (or encoded) passwords, depending on what the remote requires

It supports whatever you want to - it takes an "Opaque token" so you can choose to send a string of any form that satisfies your endpoint.

**Comment by ravindk89** [comment]
I'm assuming that string just has to be prefixed by the auth mechanism in question? Not 100% familiar with webauth mechs, but I am assuming based on what you're saying we could do any [HTTP Security Auth Scheme](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml) as long as the string following the mechanism adheres to the requirements for that mech

That is, I could also just as easily specify `SCRAM-SHA_256 realm="realm",data="data"` 

Or, for that matter, digest via `Digest username="Username",realm="realm",qop="auth, auth-int",algorithm="SHA-256",nonce="nonce",opaque="opaque"` or whatever it is.

Let me know if I'm on the right track here.

**Comment by harshavardhana** [comment]
> I'm assuming that string just has to be prefixed by the auth mechanism in question? Not 100% familiar with webauth mechs, but I am assuming based on what you're saying we could do any [HTTP Security Auth Scheme](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml) as long as the string following the mechanism adheres to the requirements for that mech
> 
> That is, I could also just as easily specify `SCRAM-SHA_256 realm="realm",data="data"`
> 
> Or, for that matter, digest via `Digest username="Username",realm="realm",qop="auth, auth-int",algorithm="SHA-256",nonce="nonce",opaque="opaque"` or whatever it is.

@ravindk89 yes this is the correct

**Comment by feorlen** [comment]
Note: the doc mentioned has moved here: [Publish Audit Logs to HTTP Webhook](https://min.io/docs/minio/kubernetes/upstream/operations/monitoring/minio-logging.html#id2)
