### ISSUE TITLE
[BUG] Wrong command in document for "Continuously Mirror a Local Directory to an S3-Compatible Host"?

### ISSUE THREAD

**Issue by fBedecarrats** [minio/docs#409]
The current documentation page on [mc mirror](https://docs.min.io/minio/baremetal/reference/minio-cli/minio-mc/mc-mirror.html) mentions:
> ## Continuously Mirror a Local Directory to an S3-Compatible Host
>Use `mc watch` with --watch to continuously mirror files from a filesystem to an S3-compatible host:
>```
>mc mirror FILEPATH ALIAS/PATH
>``` 
>- Replace FILEPATH with the full file path to the directory to mirror.
>- Replace ALIAS with the alias of a configured S3-compatible host.
>- Replace PATH with the destination bucket.

Shouldn't this read `mc mirror --watch FILEPATH ALIAS/PATH` instead of  `mc mirror FILEPATH ALIAS/PATH` ?

**Comment by ravindk89** [comment]
Yep - just need to make a small fix here.

**Comment by ravindk89** [comment]
Fixed in https://github.com/minio/docs/commit/008c35097f92c89d90fea33333c4a4e7dbdc4a83
