### ISSUE TITLE
Erasure Coding[BUG]

### ISSUE THREAD

**Issue by fidohan** [minio/docs#413]
***Now consider a Server Pool consisting of 5 nodes with 8 drives each for a total of 40 drives. Using the GCD, MinIO would create 4 erasure sets with 10 drives each. However, this distribution would result in uneven distribution with one node contributing more drives to the Erasure Sets than the others. MinIO instead creates 5 erasure sets with 8 drives each to ensure uniform distribution of Erasure Set drives per Nodes.***

As describe above, It is absolutely **even** distribution using 4 erasure sets with 10 drives while **uneven** using 5 erasure sets with 8 drives.

4 erasure sets with 10 drives each:

5 nodes|node A|node B|node C|node D|node E
-- | -- | -- | -- | -- | --
disk1 | Set 1  | Set 1  | Set 1  | Set 1  |  Set 1
disk2 | Set 1  | Set 1  | Set 1  | Set 1  |  Set 1
disk3 | Set 2  | Set 2  | Set 2  | Set 2  |  Set 2
disk4 | Set 2  | Set 2  | Set 2  | Set 2  |  Set 2
disk5 | Set 3  | Set 3  | Set 3  | Set 3  |  Set 3
disk6 | Set 3  | Set 3  | Set 3  | Set 3  |  Set 3
disk7 | Set 4  | Set 4  | Set 4  | Set 4  |  Set 4
disk8 | Set 4  | Set 4  | Set 4  | Set 4  |  Set 4

**Comment by harshavardhana** [comment]
> _**Now consider a Server Pool consisting of 5 nodes with 8 drives each for a total of 40 drives. Using the GCD, MinIO would create 4 erasure sets with 10 drives each. However, this distribution would result in uneven distribution with one node contributing more drives to the Erasure Sets than the others. MinIO instead creates 5 erasure sets with 8 drives each to ensure uniform distribution of Erasure Set drives per Nodes.**_

You are talking about documentation being wrong here? @fidohan

**Comment by harshavardhana** [comment]
This is a documentation bug 

> Now consider a Server Pool consisting of 5 nodes with 8 drives each for a total of 40 drives. Using the GCD, MinIO would create 4 erasure sets with 10 drives each. However, this distribution would result in uneven distribution with one node contributing more drives to the Erasure Sets than the others. MinIO instead creates 5 erasure sets with 8 drives each to ensure uniform distribution of Erasure Set drives per Nodes.


MinIO never creates '5' erasure sets with 8 drives. MinIO always tries to be even in terms of distribution i.e each node should participate an equal number of drives in any given set. 

This is ensured by making sure that whoever "EC" we choose should be divisible by the number of nodes. 

The documentation needs fixing.

**Comment by fidohan** [comment]
> > _**Now consider a Server Pool consisting of 5 nodes with 8 drives each for a total of 40 drives. Using the GCD, MinIO would create 4 erasure sets with 10 drives each. However, this distribution would result in uneven distribution with one node contributing more drives to the Erasure Sets than the others. MinIO instead creates 5 erasure sets with 8 drives each to ensure uniform distribution of Erasure Set drives per Nodes.**_
> 
> You are talking about documentation being wrong here? @fidohan

yes. I think this case is not right. Consider 5 nodes with 16 drives , it is the best illustration that GCD is 16 but not even distribution.

**Comment by ravindk89** [comment]
I'll just drop that whole section and point to the erasure coding calculator - trying to nail a description verbally makes little sense in retrospect.

**Comment by harshavardhana** [comment]
> I'll just drop that whole section and point to the erasure coding calculator - trying to nail a description verbally makes little sense in retrospect.

Yes agreed just remove it, explaining this is not necessary.

**Comment by ravindk89** [comment]
https://github.com/minio/docs/commit/e6895c8eaf2717f80af96228d75479724500afcb Removed.Rebuilding docs now.
