### ISSUE TITLE
Expanding Distributed TLS minio with new Server Pool needs explicit port in Expansion URL 

### ISSUE THREAD

**Issue by aglahe** [minio/docs#417]
Disclaimer: This could be just a docs issue when using TLS..but, just in case it's not.

If you expand a TLS minio deployment by adding a server pool, if you set the port in the startup cmd line, you must make sure that when adding a second server pool expansion url, to include the port.  If you don't, even though the first server pool with TLS worked fine without, when adding a second, it appears as though the machines in server pool 1 will try and reach server pool 2 machines on port :443 because of the https/TLS in the URL.

## Expected Behavior
When restarting minio with additional server pool expansion URLs, it would use the default port :9000 when using TLS

ServerPool 1 start:
server --address :9000 https://minio-test1.test.local/data{1...4}

ServerPool 1 & 2 start:
server --address :9000 https://minio-test1.test.local/data{1...4} https://minio-test2.test.local/data{1...4}

```$ mc admin info debug
●  minio-test1.test.local
   Uptime: 1 minute
   Version: 2022-01-08T03:11:54Z
   Network: 2/2 OK
   Drives: 4/4 OK

●  minio-test2.test.local
   Uptime: 1 minute
   Version: 2022-01-08T03:11:54Z
   Network: 2/2 OK
   Drives: 4/4 OK
```

## Current Behavior
```
$ mc admin info debug
●  minio-test1.test.local
   Uptime: 1 minute
   Version: 2022-01-08T03:11:54Z
   Network: 2/2 OK
   Drives: 4/4 OK

●  minio-test1.test.local
   Uptime: offline
   Drives: 0/4 OK

●  minio-test2.test.local
   Uptime: 1 minute
   Version: 2022-01-08T03:11:54Z
   Network: 2/2 OK
   Drives: 4/4 OK
```
with errors in the log saying it can't find the 'offline' test1 instance.

## Possible Solution
Not sure, could just be a docs issue.  Basically, you need to add the port used, in this case :9000 to the URLs of the cmd line.

`server --address :9000 https://minio-test1.test.local:9000/data{1...4} https://minio-test2.test.local:9000/data{1...4}`

I  can see why it happens.  Basically, even though you have told minio to use :9000 and HTTPS/TLS...if you don't include the port in the URLs, server pool 1 will try to 'reach' all those servers on :443.

But you can't use _http_ in the URL of the cmd line because you'll get, so you need to set _https_

`ERROR Unable to start the server: HTTP specified in endpoints, but the server in the local machine is configured with a TLS certificate
      > Please remove the certificate in the configuration directory or switch to HTTPS`

## Steps to Reproduce (for bugs)
1. Create 2 machines, with 4 DIRs each
2. Start the 1st Server Pool on machine 1:

server --address :9000 https://minio-test1.test.local/data{1...4}

3. Now restart the minio on machine 1 and machine 2, both with:

server --address :9000 https://minio-test1.test.local/data{1...4} https://minio-test2.test.local/data{1...4}

## Context
Basically, server pool 1 machines can't fine server pool 2 because by default, when using https it goes to port 443.  If the console is running on a different port.

## Regression
Not Sure

## Your Environment

* Version used (`minio --version`): appears to be in versions that I tested:  

    minio_version: 'RELEASE.2021-12-20T22-07-16Z'
    minio_version: 'RELEASE.2022-01-08T03-11-54Z'

* Server setup and configuration: Running inside Docker Container
* Operating System and version (`uname -a`): Docker on Centos 7, x68_64

**Comment by harshavardhana** [comment]
> @harshavardhana unless you have other intentions, i'm going to transfer this to minio/docs and work on it there

Sure I am also fixing the MinIO output in `mc` @ravindk89

**Comment by ravindk89** [comment]
Updated via https://github.com/minio/docs/commit/ea019095278b88dae47f20236df6a31cce32f0ad

https://docs.min.io/minio/baremetal/installation/expand-minio-distributed.html

Also included it as a standard practice for single pool, and updated the networking prereqs to call out that all MinIO servers should use the same listen port.
