### ISSUE TITLE
Documentation: what is allowed and forbidden to do with storage if using pre-existing data

### ISSUE THREAD

**Issue by nzsb** [minio/docs#418]
Using minio with pre-existing data.
After researching some strange behaviors and coming to issue minio/minio#8044, guess it is generally not allowed to modify the storage (FS) directly after starting minio, but I could find any explicit information about this in the documentation.
What is exactly allowed and disallowed with the backend FS? E.g. Is it allowed to read the storage directly?
Can you please document this, this is not clear for a lot of people without knowing how minio builds and maintains metadata.

**Comment by nzsb** [comment]
Thanks for your quick answer.
Yes in #8044 it is clearly stated, but I think it would make sense to add it to "Pre-existing data" section at the doc to avoid confusion.
If I understand it correctly reading is allowed, even if the objects were created with API? I think this also worths mentioning in the doc so users can depend on that.

**Comment by nzsb** [comment]
Thanks for the updated, I reviewed, the sentence "Once you start the MinIO server, all interactions with the data must be done through the S3 API." is only included in distributed mode documentation, but not in standalone.
I am confused, it is indeed possible to delete/write pre existing data after starting minio in standalone mode?
See https://github.com/minio/docs/issues/418#issuecomment-1013095335 for reference, where it was stated that it is not allowed.

**Comment by djwfyi** [comment]
@nzsb For a single node, single drive standalone setup, you can indeed create/delete files directly and MinIO picks up the changes.
