### ISSUE TITLE
Layout: Lists in tables font size

### ISSUE THREAD

**Issue by klauspost** [minio/docs#419]
It seems like list items in tables gets a bigger font (16px vs 14.4px)

For example in: https://docs.min.io/minio/baremetal/console/minio-console.html#configuration

![listtablefont](https://user-images.githubusercontent.com/5663952/151010115-758480db-0842-45cf-b673-91488d70416f.png)

**Describe the solution you'd like**

Fonts have the same size in tables.

**Describe alternatives you've considered**

Deal with it.

**Additional context**

Latest Chrome, Windows.

**Comment by ravindk89** [comment]
Have I mentioned how much I dislike CSS for these weird little isms that show up? Not sure how I missed this issue, will play around with the CSS and see what I can fix and break simultaneously.

**Comment by ravindk89** [comment]
@rushenn @kaankabalak I might actually need some help with this. Rather than continuously trying to find combinations/permutations of ul/li where this might happen, the text *should* apply to all subelements instead of at some point inheriting from the body.

Ideas?

**Comment by kaankabalak** [comment]
Hi @ravindk89, maybe something like this would work as it would apply to the selector `table.docutils` and all of its children:

```diff
diff --git a/source/_static/scss/includes/_base.scss b/source/_static/scss/includes/_base.scss
index 871d4ff..8d57174 100644
--- a/source/_static/scss/includes/_base.scss
+++ b/source/_static/scss/includes/_base.scss
@@ -144,29 +144,23 @@ table.docutils {
     box-shadow: none;
     -webkit-box-shadow: none;
     -moz-box-shadow: none;
+    font-size: .9rem;
 
     & > tbody tr th.stub {
         border: none;
         border-bottom: 1px solid $docs-item-table-border;
         color: $theme-red;
-        font-size: .9rem;
     }
 
     & > thead tr th {
         border: none;
         border-bottom: 1px solid $docs-item-table-border;
-        font-size: 1rem;
         color: $theme-red;
-        font-size: .9rem;
     }
 
     & > tbody tr td {
         border: none;
         border-bottom: 1px solid $docs-item-table-border;
-
-        & > p {
-            font-size: .90rem;
-        }
     }
 
 }
```

**Comment by ravindk89** [comment]
Aha - let me try that. Thanks @kaankabalak

**Comment by kaankabalak** [comment]
@ravindk89 sent a PR below, please let me know if any changes are required:

https://github.com/minio/docs/pull/424

**Comment by ravindk89** [comment]
https://docs.min.io/minio/baremetal/console/minio-console.html#configuration looks fixed! Thanks @kaankabalak
