### ISSUE TITLE
Clarify Object allocation to Pools

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#426]
**Summary**

We currently [document](https://docs.min.io/minio/baremetal/installation/expand-minio-distributed.html#expand-a-distributed-minio-deployment) the following behavior w.r.t. object placement in multi-pool setups:

> MinIO does not rebalance objects across the new server pools. MinIO prefers new write operations to the pool with the most free storage, *which is typically the newly added pool.*

The emphasized section is not entirely correct. The preference is *weighted* such that the % of free space is also considered.

**Goals**

List the in-scope goals

- [x] Understand how MinIO allocates objects across multiple pools
- [x] Document to an appropriate level the object allocation logic

**Non-Goals**

**Additional context**

Using this for onboarding

**Comment by klauspost** [comment]
Consider Pool A+B:

Pool A Probability =  FreeSpacePoolA / (FreeSpaceAllPools)
Pool B Probability =  FreeSpacePoolB / (FreeSpaceAllPools)

Pools are disregarded if adding the object (with parity) to any set would bring disk usage above 99% or the free inode count (if known) below 1000.

Pools that are being decommissioned are also disregarded.
