### ISSUE TITLE
Document Site Replication

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#436]
**Summary**

MinIO added [Site Replication](https://github.com/minio/minio/tree/master/docs/site-replication) as an alternative to Bucket Replication, where nearly all site-level configurations are synchronized.

Originally the feature only supported AD/LDAP, but now appears to support all three Identity Providers (minIO, OIDC, LDAP)

This project likely needs to be broken down into smaller parts to make it more approachable.

**Goals**

List the in-scope goals

- [x] Document Site Replication as a concept
- [x] Document comparison between Bucket and Site replication
- [x] Create tutorial for Site Replication using MinIO IDP
- [x] Create tutorial for Site Replication using OIDC (Keycloak)
- [x] Create tutorial for Site Replication using AD/LDAP
- [ ] Create tutorial for restoring a site after complete data loss (BC/DR)

**Non-Goals**

- Refactoring existing replication content
- Updating existing replication tutorials

**Additional context**
The restoration procedure will likely require some careful testing and QA to ensure we've fully captured the required work for bringing a site back up.

**Comment by djwfyi** [comment]
Not creating separate docs for the identity managers. Site replication merely requires that all sites use the same one. Differences of what replicates across sites that does vary between the identify managers is noted in the site replication overview doc.
