### ISSUE TITLE
Improve documentation of Policy Variables

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#437]
**Summary**

MinIO supports using variables when constructing a policy document to create programmatic policies based on details like the incoming username. This is particularly useful for locking down access to specific buckets or bucket prefixes based on the incoming user access key/credentials.

The [NextGen Docs](https://docs.min.io/minio/baremetal/security/minio-identity-management/policy-based-access-control.html#) do not currently discuss how to use these variables. They are captured only on the [legacy docs](https://docs.min.io/docs/minio-multi-user-quickstart-guide.html)

**Goals**

List the in-scope goals

- [ ] Document the usage of policy variables in Resources for programmatic access control
- [ ] Update the identity-provider specific pages with the supported variables for that IDP
- [ ] Create example policies for quick reference

**Non-Goals**

Any refactoring or rewriting of existing IAM content

**Additional context**

**Comment by djwfyi** [comment]
Pull from legacy docs.

**Comment by ravindk89** [comment]
Re-scoping a bit:

- I will pull the policy docs in as part or #476 
- This ticket will go to Nice to Have as a general improvement on how to use policy variables in policies

**Comment by djwfyi** [comment]
I think this might be done?
https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#policy-variables

@ravindk89 Thoughts?

**Comment by ravindk89** [comment]
I think so. Originally I think I had hoped to go farther, but lets not add more to an already near-full pot.
