### ISSUE TITLE
Add Console guides to all MinIO Tutorials

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#441]
**Summary**

The MinIO Console provides a clean and sometimes simplified pathway for configuring MinIO features such as lifecycle management or replication.

These routes are largely undocumented in the next-gen docs. Ideally tutorials should have both the Console and the CLI routes, with Console given priority - this better addresses environments where the MinIO administrator does not have CLI access to the MinIO deployment _or_ would prefer a GUI environment for performing management, etc..

**Goals**

List the in-scope goals

- [ ] Assemble a list of tutorials that require Console-specific guidance
- [ ] Update documentation one-at-a-time for each line item

**Non-Goals**

This is not an all-at-once ticket. We can re-use the issue and take down one tutorial at a time until everything has been updated appropriately.

**Additional context**

**Comment by djwfyi** [comment]
Closing per discussion
