### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#461]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
- Rename `master` branch to `main`.
- Make the `main` branch the default branch.
- Ensure that branch protection from `master` applies to `main`.

**Describe alternatives you've considered**
`Main` has become the new standard for default branches in git. No real reason to consider alternatives.

**Additional context**
This brings MinIO docs in line with modern practices for branch naming conventions.

**Comment by ravindk89** [comment]
We're planning on doing this in the near future. Should not impact anything, but raising this just in case someone out there has built scripts against our master branch.

**Comment by harshavardhana** [comment]
git still creates master as default branch name, it's GitHub's decision to keep main instead of master.

**Comment by ravindk89** [comment]
Yeah, we might as well keep it consistent - `docs-k8s` is `main` anyways. 

AFAIK we have no scripts relying on this, it's just docs so it shouldn't impact anything - @harshavardhana if there's something you know that we hook into that would be good to know, I don't think we have any chron jobs that auto-pull or rebuild these docs right now

**Comment by harshavardhana** [comment]
> Yeah, we might as well keep it consistent - `docs-k8s` is `main` anyways.
> 
> AFAIK we have no scripts relying on this, it's just docs so it shouldn't impact anything - @harshavardhana if there's something you know that we hook into that would be good to know, I don't think we have any chron jobs that auto-pull or rebuild these docs right now

there should be none.

**Comment by djwfyi** [comment]
This has been done as part of the new docs release.
