### ISSUE TITLE
Document ILM Behavior with edge-case versioning scenarios

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#475]
**Summary**

During a troubleshooting session we encountered an interesting situation where a user had a folder with multiple delete markers for objects - that is, a single object had several delete markers.

ILM Expiry supports deleting objects with only delete markers remaining, but both ours and S3's behavior here is to delete at most *one* (the latest I think) of those delete markers.

This raised the question of trying to capture other types of unusual  versioning behavior and how it might interact with ILM. 

Will need to lean heavily on @krisis , @vadmeste , @kannappanr , and @kanagarajkm for some guidance in determining what the weird versioning states are and how ILM interacts with those states.

**Goals**

List the in-scope goals

- [ ] Assemble a list of "weird" versioning states
- [ ] Refine ILM expiry/transition behavior docs based on observed behavior during those states
- [ ] Create additional documentation if required for avoiding those states (where it makes sense to)

**Non-Goals**

We might need to keep this open and do several smaller PR commits as we find these edge cases, as they are not always apparent and may only occur under certain workloads (e.g. Spark w/ suboptimal pipelines or committer behaviors).

**Additional context**

**Comment by djwfyi** [comment]
Starting with RELEASE.2022-08-22T23-53-06Z, DeleteMarkers are idempotent.
I don't think this is needed any longer.

@ravindk89 thoughts?

**Comment by djwfyi** [comment]
Think we're good not doing this.
