### ISSUE TITLE
List global flags under separate page.

### ISSUE THREAD

**Issue by bh4t** [minio/docs#515]
While reviewing the mc command documentation, @abperiasamy 
suggested we should list the global flags(listed below) for each mc 
command under a separate page and add a reference to this page 
under the per mc command to avoid redundancy.

> _[Global Flags](https://docs.min.io/minio/baremetal/reference/minio-mc/mc-find.html#id3)
> --debug
> Optional
> Enables verbose output to the console.
> 
> For example:
> 
> mc --debug COMMAND
> --config-dir
> Optional
> The path to a JSON formatted configuration file that mc uses for storing data. See [Configuration File](https://docs.min.io/minio/baremetal/reference/minio-mc.html#mc-configuration) for more information on how mc uses the configuration file.
> 
> --JSON
> Optional
> Enables [JSON lines](http://jsonlines.org/) formatted output to the console.
> 
> For example:
> 
> mc --JSON COMMAND
> --no-color
> Optional
> Disables the built-in color theme for console output. Useful for dumb terminals.
> 
> --quiet
> Optional
> Suppresses console output.
> 
> --insecure
> Optional
> Disables TLS/SSL certificate verification. Allows TLS connectivity to servers with invalid certificates. Exercise caution when using this option against untrusted S3 hosts.
> 
> --version
> Optional
> Displays the current version of [mc](https://docs.min.io/minio/baremetal/reference/minio-mc.html#command-mc).
> 
> --help
> Optional
> Displays a summary of command usage on the terminal._

**Comment by ravindk89** [comment]
This shouldn't be too difficult ... we already have https://docs.min.io/minio/baremetal/reference/minio-mc.html#global-options , so it would be a question of removing the lists on each individual reference page and just linking up to the global options instead.

**Comment by ravindk89** [comment]
The scale here is pretty big, but its mostly removing and re-linking - I think this is still "tiny" from that perspective.

**Comment by djwfyi** [comment]
Closed by PR #541 .
