### ISSUE TITLE
disable-multipart flag missing from mc-mv page

### ISSUE THREAD

**Issue by bh4t** [minio/docs#516]
Description/ Example for disable-multipart flag is missing 
from mc-mv page. Following description is mentioned
under the mv command on the terminal.

> --disable-multipart                disable multipart upload 

Example:

> Move a text file to an object storage and disable multipart upload feature.

      $ mc mv --disable-multipart myobject.txt play/mybucket

**Comment by ravindk89** [comment]
ToDo:

- Add `--disable-multipart` to https://docs.min.io/minio/baremetal/reference/minio-mc/mc-mv.html#parameters
- Thought: We don't currently talk about what multipart uploads are. Link to S3 docs for now?
