### ISSUE TITLE
[Release] Update docs for RELEASE.2022-08-11T04-37-28Z 

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#529]
Release [RELEASE.2022-08-11T04-37-28Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-08-11T04-37-28Z) has changes that impact the docs:

- [x] The healing process for buckets or sites with replication is now prompted when running `mc stat`, `mc cat`, or `mc ls`. Update the site replication and bucket replication docs. [PR #15501](https://github.com/minio/minio/pull/15501)
- [x] ~New feature allows you to enable object locking when creating a bucket [PR #15505](https://github.com/minio/minio/pull/15505)~ - This is for helm, will not document in the current docs.

**Comment by ravindk89** [comment]
@kannappanr @harshavardhana it would be excellent if we could find a way via github actions to automatically create these tickets on release for issues that are marked as 'Documentation Needed' or something. 

Manually reviewing release queues for our various products is somewhat inefficient.
