### ISSUE TITLE
Use blkid, not manual labels in the docs

### ISSUE THREAD

**Issue by udf2457** [minio/docs#531]
At present [in the docs ](https://docs.min.io/minio/baremetal/installation/deploy-minio-distributed.html), we are presented with a tutorial that is based upon manual labelling of drives (e.g. `mkfs.xfs /dev/sdb -L DISK1`).

There is a reason why modern sysadmin prefers to use the UUID values provided by `blkid` namely that it uses a UUID which is effectively globally unique.   That means that you avoid all sorts of problems associated with manual labels, such as avoiding naming collisions, such as avoiding issues when physical drives may be plugged into a different system and many others.

`mkfs.xfs /dev/xy` creates UUIDs by default, so `-L` can be omitted and then the sysadmin just runs `blkid` to view the UUID to insert into `fstab`

**Comment by harshavardhana** [comment]
Labels are mentioned for ease of use and understanding. Using UUIDs is cumbersome and has no real benefits over labels.

Unless humans are not managing the drives such as CSIs in k8s world. In practice we have seen almost all sysadmins get mounting UUID wrong.

Labels are simply "human" friendly. We can definitely mention that UUID is also preferred however for ease of use labeling is much simpler on bare metal systems.
