### ISSUE TITLE
Limit to the number of buckets (MinIO RELEASE.2022-09-17T00-09-45Z)

### ISSUE THREAD

**Issue by harshavardhana** [minio/docs#548]
## Description
limit number of buckets to 500k

# Summary

- Add limit to the reference pages for `mc mb`
- We need to import the Limits page from the legacy docs, should include this here
- Need to update training materials as well.

**Comment by ravindk89** [comment]
@harshavardhana looking at the code, limit is 500K buckets. Description says 250K, but generic-handlers.go says otherwise. Just want to check.

**Comment by ravindk89** [comment]
That same PR also notes maximum object size of 50TiB - was that intentional?

**Comment by harshavardhana** [comment]
> That same PR also notes maximum object size of 50TiB - was that intentional?

Yes it is not 5TiB seems like it has been 50TiB if you use multipart.
