### ISSUE TITLE
Update the Docs UI search box to support the Algolia's DocSearch

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#552]
**Summary**

Our current search box in the Sphinx docs needs to be updated to work with Algolia's DocSearch function.

The `docs-ia` branch already has `algolia.css` and `algolia.js` files as a start.

Follow the instructions from Algolia here: https://docsearch.algolia.com/docs/DocSearch-v3#implementation
For styling, refer to https://docsearch.algolia.com/docs/styling

**Comment by rushenn** [comment]
@djwfyi Can you provide the new Algolia application ID?

Also, do we need to credit them? I'm updating the overall Algolia search UI to match our theme, so just wondering is it okay to remove their branding.

**Comment by djwfyi** [comment]
App ID: E1CSOK3UC2

We are using their free DocSearch tool, and their response is:
> All we ask in exchange is that you keep the "Search by [Algolia](https://www.algolia.com/)" logo displayed next to the search results.

See https://docsearch.algolia.com/docs/DocSearch-program#how-much-does-it-cost.
