### ISSUE TITLE
Documentation inconsistency for "Server-Side Object Encryption with Hashicorp Vault Root KMS"

### ISSUE THREAD

**Issue by tsohst** [minio/docs#580]
## Current Behavior
https://min.io/docs/minio/linux/operations/server-side-encryption/configure-minio-kes-hashicorp.html?ref=docs-redirect#deploy-minio-and-kes-with-server-side-encryption-using-hashicorp-vault-for-production

Documentation is having multiple inconsistencies

## Expected Behavior
No inconsistencies in documentation

## Possible Solution
* /etc/systemd/system/kes.service referres to 
```
User=kes
Group=kes
```
* But below, we create the user/group
```
groupadd -r kes-user
useradd -M -r -g kes-user kes-user
```

* "Local Development" is configuring `mlock`
```
sudo setcap cap_ipc_lock=+ep $(readlink -f $(which kes))

kes server --mlock  \
            --config=|kesconfigpath|kes-config.yaml  \
            --auth=off
```
* Production just starts the server
`ExecStart=/usr/local/bin/kes server --config=/etc/kes/config.yaml`

* `/opt/kes/config` is created in Production docs, but is no where referenced

* `kes tool` not exisits
  * `kes tool identity of /opt/minio/certs/minio-kes.cert`
  * Error: "tool" is not a kes command. See 'kes --help'
  * It's `kes identity of /minio/certs/public.crt`

* `Vault Engine V2` missing `}`
```
path "kv/data/*" {
      capabilities = [ "create", "read"]

path "kv/metadata/*" {
      capabilities = [ "list", "delete"]
```
```
path "kv/data/*" {
      capabilities = [ "create", "read"]
}
path "kv/metadata/*" {
      capabilities = [ "list", "delete"]
}
```
* Maybe also reference that you've need to enable approle auth first
```
vault auth enable approle
```
* admin entity needs to be defined in kes.config, else it won't start
```
admin:
  identity: disabled 
```
* Engine and version needs to be defined
```
    engine: "minio-kes"    # The path of the K/V engine - e.g. secrets. If empty, defaults to: kv. (Vault default)
    version: "v2"   # The K/V engine version - either "v1" or "v2". The "v1" engine is recommended.
```
https://github.com/minio/kes/blob/master/server-config.yaml
* Maybe here is more, so a review of the document would be great.

**Comment by ravindk89** [comment]
Addressing all points except:

> `/opt/kes/config` is created in Production docs, but is no where referenced

It's where the KES certs are stored, at least presumably in that procedure. The procedure begins with creating `/opt/kes/certs`, `opt/kes/config`, and `opt/minio/certs`

If you look at the config, it mentions the `/opt/kes/certs` path at minimum.

making a few other fixes for consistency.

As far as a larger pass, we will do that - but not right away. There are other tutorials that need some attention first before we re-tread these ones. We do appreciate the assistance in identifying these issues.
