### ISSUE TITLE
[BUG] mc admin trace doesn't use HTTP TRACE 

### ISSUE THREAD

**Issue by krisis** [minio/docs#607]
**Describe the bug**
`mc admin trace` doesn't use HTTP TRACE type request internally as mentioned here - https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-trace.html#command-mc.admin.trace

We need to remove this mention.

**Comment by ravindk89** [comment]
https://github.com/minio/docs/commit/a8bf5a00377c614d502825ce35ead61f9ff05684

Fixed, should be updated shortly.

**Comment by djwfyi** [comment]
Already fixed per @ravindk89 's comment above.
