### ISSUE TITLE
[Release] Console v0.21.2

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#635]
Console [v0.21.2](https://github.com/minio/console/releases/tag/v0.21.2) has changes that impact the docs.

- [ ] New labels for "Access Keys" throughout and other style/visual changes [PR #2428](https://github.com/minio/console/pull/2428)
- [ ] Tier status icon indicators have improved accessibility [PR #2409](https://github.com/minio/console/pull/2409)

**Comment by ravindk89** [comment]
Note: `mc admin user svcacct` remains unchanged, so there is a divergence between Console and mc at this time.

**Comment by ravindk89** [comment]
Note that we do not currently have screenshots of the individual tiers in Console, so nothing to update there at this time.
