### ISSUE TITLE
Add `mc support callhome` command

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#655]
[PR 4372](https://github.com/minio/mc/pull/4372) adds the `mc support callhome` commands, which are ready to add to the docs.

## PR Summary

- Remove `support logs enable|disable|status|show`
- Make `support logs` behave like `upport logs show`
- Enhance `support callhome` to allow configuration of both periodic diagnostics and real-time log push with the same command
- This will be achieved by adding two bool flags `--diag` and `--logs`
- If none of these flags are passed, the action specified by the arg (`enable|disable|status`) will be performed for both the features

## Tasks
- [x] Add `mc support callhome` command
- [x] Remove subcommands from `mc support logs`

**Comment by anjalshireesh** [comment]
@djwfyi second point related to `support logs` will change further because of https://github.com/minio/mc/pull/4381 currently under review.

There won't be any `support logs` command. The command to show minio logs will now be `mc admin logs`

**Comment by djwfyi** [comment]
> @djwfyi second point related to `support logs` will change further because of [minio/mc#4381](https://github.com/minio/mc/pull/4381) currently under review.
> 
> There won't be any `support logs` command. The command to show minio logs will now be `mc admin logs`

Addressed by #663
