### ISSUE TITLE
`ilm rule` and `ilm tier` subcommands

### ISSUE THREAD

**Issue by krisis** [minio/docs#662]
**Summary**
https://github.com/minio/mc/pull/4385 aims to make the connection between tiering and ILM more obvious and discoverable.
This is in part done by moving `admin-tier` subcommands into `ilm-tier` subcommand hierarchy. Additionally, ILM rule CRUD operations are moved into `ilm-rule` subcommand to make the intent of those subcommands explicit.

Following example should help see the motivation for this change clearly.

- Add a lifecycle rule with a transition and a noncurrent version transition action for objects with prefix `doc/` in `mybucket`.
```shell                                                                                                                               
     $ mc ilm tier add minio myminio MINIOTIER-1 --endpoint https://warm-minio-1.com \                                          
         --access-key ACCESSKEY --secret-key SECRETKEY --bucket bucket1 --prefix prefix1                                        
                                                                                                                                    
     $ mc ilm rule add --prefix "doc/" --transition-days "90" --transition-tier "MINIOTIER-1" \                                 
         --noncurrent-transition-days "45" --noncurrent-transition-tier "MINIOTIER-1" \                                         
         myminio/mybucket/                                                                                                                          
```

**Goals**

List the in-scope goals

- [x] Update docs to reflect the new position of `mc ilm` subcommands under `mc ilm rule`
- [x] Update docs to reflect the new position of `mc admin tier` subcommands under `mc ilm tier`.

**Non-Goals**

List any items that are out of scope

**Additional context**

**Comment by djwfyi** [comment]
Note: not yet included in an mc release
