### ISSUE TITLE
`mc replicate` and `mc admin bucket remote` subcommands

### ISSUE THREAD

**Issue by poornas** [minio/docs#681]
**Summary**

remote target management for replication is being brought under `mc replicate add|update|rm` to make replication setup a one step process - instead of a remote ARN, the --remote-bucket flag will have the target url and credentials.

**Goals**

1. eliminate `mc admin bucket remote add|update|rm|ls` commands
2. `mc replicate add alias/bucket --remote-bucket <arn>` -> `mc replicate add alias/bucket --remote-bucket <target-url>` where <target-url> like http://minio:minio123@localhost:9004/bucket 
3. `mc replicate update alias/bucket --remote-bucket <target-url>` for credentials change or other remote target flag management
4. `mc replicate rm alias/bucket` - no changes. This will automatically remove the underlying remote target
5. `mc replicate status alias/bucket` - will report the endpoint of remote target.All additional flags pertaining to remote target will be visible in --json mode
6. Update permissions needed to run `mc replicate` commands to include madmin:SetBucketTarget and madmin:GetBucketTarget

https://github.com/minio/mc/pull/4403, https://github.com/minio/mc/pull/4412
 
List the in-scope goals

- [x] Update docs for `mc replicate` subcommmands and `mc admin bucket remote` subcommands
- [x] Make permissions needed for `mc replicate` clear to include the admin permissions needed for managing target
- [x] Retain reference to older docs for backward compatibility with previous releases of minio [https://github.com/minio/minio/pull/16221 to be part of upcoming release]

**Non-Goals**

List any items that are out of scope

**Additional context**

**Comment by djwfyi** [comment]
Partially completes #691
