### ISSUE TITLE
Improve ILM Tier documentation on Storage Classes

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#699]
**Summary**

Our current ILM Tiering documentation does not mention the use of `--storage-class` outside of S3 and MinIO.

On further inspection and discussion, we passthrough the storage class to the underlying Go libraries for Azure/GCP/AWS. This allows setting per-tier storage classes for the remote storage - though we can only support those storage tiers with immediate retrieval (no latency or rehydration on GET).

We must update the documentation to explicitly call out this functionality. We must also include guidance on the remote storage for those providers (e.g. Azure) where the storage configuration can be incompatible with tiering.

**Goals**

List the in-scope goals

- [ ] Update ILM Tiering documentation for MinIO, S3, GCS, and Azure to correct usage of `--storage-class`
- [ ] Update `mc ilm tier add --storage-class` documentation
- [ ] Include per-provider guidance on remote storage configurations and default storage classes

**Non-Goals**

Further iteration or exploration of remote tiering configurations

**Comment by nirav-chotai** [comment]
@ravindk89 , when you say, "...though we can only support those storage tiers with immediate retrieval (no latency or rehydration on GET).", does this will support and work for all Storage classes from GCS?

Based on https://cloud.google.com/storage/docs/storage-classes
_The following aspects apply to all storage classes:
- Low latency (time to first byte typically tens of milliseconds)._

**Comment by krisis** [comment]
@nirav-chotai it should work if the latency is as advertised and is acceptable for you use case. I haven't tested tiering objects to a GCS bucket backed tier with `ARCHIVE` storage-class type, so I can't confirm if it works.

**Comment by ravindk89** [comment]
@nirav-chotai this is somewhat of a philosophical point - our docs will recommend non-archival tiers for all supported providers, but users can always experiment further to validate the latency guarantees or retrieval behavior advertised by the provider of choice
