### ISSUE TITLE
After completing decommission, must restart before adding new pool

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#702]
Per issue on SUBNET:

After completing a pool decommission and drain, it is required to restart MinIO with the remaining existing pools prior to adding any new pools to the deployment.

- [x] Add note to decommission docs that the server must be restarted before making any additional changes
- [x] Add note to the expansion docs that any decommission in progress must run to completion and the server be restarted with remaining existing pools before expanding to a new pool.

**Comment by harshavardhana** [comment]
Not a bug add a new pool and then decommission.
