### ISSUE TITLE
[Community request] Add a page covering deleting objects

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#741]
There are many moving factors to consider when deleting an object.
Currently, the information about deleting is spread across a number of topics.

- [x] Create a new page under `Administration > Object Management` for `Object Deletion`
- [x] Clarify when objects delete from the drive vs. when a delete marker is added
- [x] Add scenarios for versioned objects, locked objects, and lifecycle management rules

**Comment by RVerduijn** [comment]
Please also include clarification on how this works for legal-hold and retention.

**Comment by ravindk89** [comment]
Tracking where we already cover this:

- https://min.io/docs/minio/linux/administration/object-management/object-retention.html#interaction-with-versioning
- https://min.io/docs/minio/linux/administration/object-management/object-retention.html#interaction-with-lifecycle-management
- https://min.io/docs/minio/linux/administration/object-management/object-lifecycle-management.html#id1

@djwfyi I kind of wonder if this should be under `Developers` as something like `Basic Operations` where we cover PUT, GET, HEAD, LIST, and DELETE or something.

We could also just add an H1 to the top-level "Object Management" page that goes over Object Deletion and summarizes + links to the relevant pages.

**Comment by ravindk89** [comment]
With further discussion, we'll try this as a two-pronged approach.

The first "fast" prong is having a paragraph or two summarizing how deletes work with versioning and retention on the Object Management page.

The second prong is having a dedicated section for Developers as "Core Concepts" where we can discuss read, write, list, and delete. That will take longer.

**Comment by djwfyi** [comment]
Added Issue #752 for stage 2 suggestion.
