### ISSUE TITLE
Document versioning prefix exclusion

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#760]
# Summary

We added a feature a little while back that allows exclusion of prefixes from versioning. This primarily helps Spark/Hadoop or similar workloads that do a lot of PUT/GET/DELETEs on a single file namespace - with versioning this results in a build-up of versions that can slow down listing over time. 

the `mc version enable ALIAS/BUCKET --excluded-prefixes "prefix,[prefix,...]"` argument adds this from the commandline. The MinIO Console may also have prefix exclusion.

There are a few quirks:

- this doesn't work (or shouldn't work) on a bucket with object locking enabled
- Adding or removing prefixes requires specifying the entire set of excluded prefixes. using `mc version info --json` lets you pull down the current list of excluded prefixes
- Wildcard matching matters. `"/foo"` will only match the prefix `ALIAS/BUCKET/foo/*`. Needs testing

**Comment by feorlen** [comment]
@ravindk89 I'll pick up this one

**Comment by ravindk89** [comment]
Thus it is yours

**Comment by feorlen** [comment]
The same commit that added `--excluded-prefixes` also created `--exclude-folders`, invoked like so:
```
mc version enable --exclude-folders local/test-bucket
```
It prevents versioning of anything whose name ends in `/`, so basically folders. @krisis gave me a lot of detail on both, I'm testing `--exclude-folders` so I can doc it as well.
