### ISSUE TITLE
Add reference docs for `mc du`

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#764]
**Summary**

We should add reference for the `mc du` command. We often reference it for support cases where users want to know the immediate real data usage and distribution of a bucket or prefix, vs waiting for the Scanner to walk those paths.

**Goals**

- [ ] Add the mc du reference page to docs
- [ ] Update the mc reference index page to include mc du

**Non-Goals**

Anything else on usage outside of a reference context

**Comment by feorlen** [comment]
Lost the final commit due to network outage. It's in https://github.com/minio/docs/pull/789 instead.
