### ISSUE TITLE
Add blurb on NTP Time Sync for hosts

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#778]
**Summary**

Operations in any distributed system tend to require accurate system clocks.

Most hosts should have a built-in way to synchronize time, and we should add that to our software checklist. 

Essentially ensuring that ntp or something similar is running, and that all nodes have the same UTC datetime.

Skew in clocks can result in a variety of issues, including internode issues.

**Goals**

- [x] Update [the Software Checklist](https://min.io/docs/minio/linux/operations/checklists/software.html) with system clock sync
- [x] Maybe talk about checking ntp and timedatectl ? 
- [x] This could be good to add as a pre-requisite to our deploy tutorials, though it somewhat falls under the "Make sure your nodes aren't broken before installing MinIO" kind of rule

**Comment by djwfyi** [comment]
Check different Linux upstreams to see how they handle.
