### ISSUE TITLE
Update KES Errors to resolve permissions on February 2023+ releases

### ISSUE THREAD

**Issue by tsohst** [minio/docs#779]
* Minio is currently not starting in our environment after upgradeing to the newest release in combination with KES
* `Error: not authorized: insufficient permissions (kes.Error)`
* We are unable to find out if there was a change in minio which needs more permissions to use KMS?
  * API-Documentation of KES did not change since 2022, and we've upgraded from a Jan 23 release to the newest
  * https://github.com/minio/kes/wiki/Server-API#api-overview
* These endpoints we're the only one needed before and it seems like minio needs more with newer releases?
 ```
    - /v1/key/create/* 
    - /v1/key/generate/* 
    - /v1/key/decrypt/*
```

## Expected Behavior
* Minio should start as usual

## Current Behavior
```
Mär 28 13:51:57 minio2 minio[13835]: Documentation: https://min.io/docs/minio/linux/index.html
Mär 28 13:51:57 minio2 minio[13835]: API: SYSTEM()
Mär 28 13:51:57 minio2 minio[13835]: Time: 11:51:57 UTC 03/28/2023
Mär 28 13:51:57 minio2 minio[13835]: DeploymentID: e425c60c-3de5-42d3-81c5-09a620eaf8c6
Mär 28 13:51:57 minio2 minio[13835]: Error: not authorized: insufficient permissions (kes.Error)
Mär 28 13:51:57 minio2 minio[13835]:        5: internal/logger/logger.go:258:logger.LogIf()
Mär 28 13:51:57 minio2 minio[13835]:        4: cmd/api-errors.go:2280:cmd.toAPIErrorCode()
Mär 28 13:51:57 minio2 minio[13835]:        3: cmd/api-errors.go:2305:cmd.toAPIError()
Mär 28 13:51:57 minio2 minio[13835]:        2: cmd/healthcheck-handler.go:134:cmd.LivenessCheckHandler()
Mär 28 13:51:57 minio2 minio[13835]:        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```

## Possible Solution
* After removing the "policy" section in kes config and enable admin identity minio is working again.

## Steps to Reproduce (for bugs)
* Upgrade to RELEASE.2023-03-24T21-41-23Z
* restarting minio service results in error above
* upgrade KES to 2023-02-15T14-54-37Z _did not fix it_

## Context
* Upgraded MINIO from a release of january to: 
  * minio version RELEASE.2023-03-24T21-41-23Z (commit-id=74040b457b50417b58eae7cb17c63428a0e2dd44)
  * kes 2023-02-15T14-54-37Z (commit=8ce403b264e3c6fafb94577dd1c59ae811963e43)

## Your Environment
**We have set the following Env vars for minio regaring KES:**
```
MINIO_KMS_KES_ENDPOINT
MINIO_KMS_KES_ENDPOINT
MINIO_KMS_KES_CERT_FILE
MINIO_KMS_KES_KEY_FILE
MINIO_KMS_KES_CAPATH
MINIO_KMS_KES_KEY_NAME
```
* **This was our kes-config before the upgrade**
```
address: 0.0.0.0:7373

admin:
  identity: disabled 

root: disabled

tls:
  key:  /minio/certs/private.key
  cert: /minio/certs/public.crt

policy:
  minio-kes:
    allow:
    - /v1/key/create/*   
    - /v1/key/generate/* 
    - /v1/key/decrypt/*
    identities:
    - ABCD

log:
  error: on
  audit: on

keystore:
  vault:
    endpoint: https://vault:8200
    engine: "minio-kes"    
    version: "v2"   
    approle:
      id: "YYYYYYY"     
      secret: "ZZZZZZZ"
      retry: 15s
    status:
      ping: 10s
```
* **This is our kes-config AFTER the upgrade to fix the issue**
```
address: 0.0.0.0:7373

admin:
  identity: ABCD

root: disabled

tls:
  key:  /minio/certs/private.key
  cert: /minio/certs/public.crt

log:
  error: on
  audit: on

keystore:
  vault:
    endpoint: https://vault:8200
    engine: "minio-kes"    
    version: "v2"   
    approle:
      id: "YYYYYYY"     
      secret: "ZZZZZZZ"
      retry: 15s
    status:
      ping: 10s
```

**Comment by tsohst** [comment]
> @tsohst just to confirm, what January release were you using?

We came from RELEASE.2023-01-02T09-40-09Z

**Comment by harshavardhana** [comment]
> admin:
>   identity: ABCD

This is also the correct way to do it, calling MinIO connection as 'admin:' is the correct approach if you don't want to play around with `allow:` policies.

**Comment by ravindk89** [comment]
So we'll do two things here:

1) Update the policy guidance to include the recommended `admin` approach and the more constrained `policy` approach
2) Use this as a chance to do the API-key approach and simplify the setup further

It _looks_ like the February release forward is where this change happens.. That recency is probably why we are not seeing more of this in the wild. Updating the docs here will help.

**Comment by tsohst** [comment]
> You need to add
> 
> ```
> allow:
>     - /v1/key/create/*   
>     - /v1/key/generate/* 
>     - /v1/key/decrypt/*
>     - /v1/key/list*
>     - /v1/status
>     - /v1/metrics
> ```

Can confirm it is working with these permissions.

**Comment by ravindk89** [comment]
The remainder of this work is covered in #912
