### ISSUE TITLE
[FEATURE] - Document how to deploy MinIO via ArgoCD/GitOps with Helm

### ISSUE THREAD

**Issue by cniackz** [minio/docs#798]
**Is your feature request related to a problem? Please describe.**

This is not related to a problem but to a necesity of helping users in a better way, lately I have seen more and more users using ArgoCD and they all have similar questions when performing the deploy. And all of them want to use `helm` on top of ArgoCD, during those meetings, I have seen how this is possible and it can work, but I never had a chance to do it my-self, so I just have part of the procedure. At the end, what I am requesting is to start formal documentation on how this can be achieved, so that when next customer comes with same questions, we can simple redirect the customer to read our Documentation on ArgoCD integration with Helm.

**Describe the solution you'd like**
A clear and concise description of what you want to happen: To have formal documentation on how to deploy MinIO via ArgoCD/Helm.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered: I have heard from some customers, that Kustomize could be an option and even OperatorHub, but at the end all of the customers I have been in touch with, are using just Helm, so if someone knows more from Kustomize and ArgoCD or OperatorHub and ArgoCD, that would be the alternatives.

**Additional context**
Add any other context or screenshots about the feature request here: I just have a small wiki to show how to use Helm and that has been working for old versions of Operator and MinIO and for new versions as well, this wiki can help get ArgoCD working but it is just half of the equation, as I would like to see ArgoCD part also documented and some screenshots on how this can be used, maybe we can start with some initial tags or places to expose this and then we can share and get feedback from the users: https://github.com/cniackz/public/wiki/How-to-install-MinIO-Using-Helm-in-Kubernetes

### Tested locally, you can get steps from:

https://github.com/minio/wiki/wiki/How-to-deploy-MinIO-with-ArgoCD-in-k8s

**Comment by ravindk89** [comment]
@kannappanr one thing to follow-up here is on the helm side for tenant deployment. we can in detail talk about values.yaml and document the mapping, but ideally we would find a way to do this via annotations and auto-generating some level of reference. Otherwise it is far too easy for the docs to fall out of sync w/ the core product.
