### ISSUE TITLE
Add info about mc / server versions for fs migration

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#805]
The Gateway migration doc has info on the version of `minio` to use, but we need to add information about the version of `mc` users need to pin to for continuing to work with FS mode.

- [ ] Research the `mc` version number to use for continuing to work with Gateway/FS
- [ ] Add the info about the recommended `mc` version to the `operations/install-deploy-manage/migrate-fs-gateway` doc

**Comment by djwfyi** [comment]
`mc` version should likely be the last one before 10-29-2022.

**Comment by allanrogerr** [comment]
mc version should be **newer** and as close as possible to the minio server version.
```
mc --version
mc admin info <alias> --json | jq -r '.info.servers[].version'
```
where `<alias>` needs to be replaced with the alias for your minio instance
