### ISSUE TITLE
[BUG] gateway/fs migration docs

### ISSUE THREAD

**Issue by poornas** [minio/docs#818]
**Describe the bug**

Some misleading steps in the docs needs to be clarified/removed
https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html and https://blog.min.io/minio-gateway-migration/ 

- Export/Import the existing deployment’s configurations with `mc admin config export/import` only to fs. For gateway all config are in env. vars. MINIO_CACHE_* and MINIO_GATEWAY_SSE env are no longer relevant in the newer cluster - all other env.var can be brought in as is
- Export/Import bucket metadata and iam assets applies only to fs mode
- Tiering not available in gateway mode nor in FS mode. Tiering is only available in SNSD, SNMD and MNMD

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ravindk89** [comment]
Based on initial walkthrough:

- gateway is envvar only and most should be 1:1 transfer.
- We can just drop the tiering section

Maybe tabs to deal with FS vs Gateway? Or make them two procedures on the same page with shared steps.
