### ISSUE TITLE
Add information about data compression

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#830]
Data compression configuration is currently missing form the docs.
Add a page under Administration/Object Management about the feature.

Data compression is a global configuration option, but per-bucket.
It can be modified or disabled at any time.

Refer to the following resources:
- https://github.com/minio/minio/tree/master/docs/compression
- https://blog.min.io/transparent-data-compression/

**Comment by ravindk89** [comment]
https://github.com/minio/docs/commit/bb1600952e953a1632538fcc0d8600ce1563bab9 wraps this out right @feorlen ?

**Comment by feorlen** [comment]
> [bb16009](https://github.com/minio/docs/commit/bb1600952e953a1632538fcc0d8600ce1563bab9) wraps this out right @feorlen ?

Ooo yup, forgot to tag the PR correctly. I'll close.
