### ISSUE TITLE
Add way to link to complementary docs

### ISSUE THREAD

**Issue by djwfyi** [minio/docs#842]
We need to add a way to link to complementary products from the MinIO docs.

We are not planning to add links to the top nav across sites.

- [ ] Modify the Sphinx theme to add a "Go To" dropdown as on slides 4 and 5 of the [mockup](https://xd.adobe.com/view/ef6838e9-6f88-4827-8804-b10f40b17d88-ba3b/screen/7034c834-1261-4cde-bd1f-04cc17bdbce9)
- [ ] Have an easy way to modify the list of doc sites (should just be MinIO and KES to start)

**Comment by rushenn** [comment]
@djwfyi I think the mobile position of the dropdown needs to be adjusted to avoid overlapping with the TOC. I will move the dropdown to the top-bar on mobile as shown in the image below.

![doc](https://user-images.githubusercontent.com/13393018/236181498-4a766b58-880b-40cb-86e1-032d167cc999.png)

**Comment by djwfyi** [comment]
I'm okay with this placement.
@ravindk89 and @feorlen any thoughts?

**Comment by feorlen** [comment]
> I'm okay with this placement.
Agree 👍🏻

**Comment by ravindk89** [comment]
It gets us moving for now and that's enough.
