### ISSUE TITLE
[BUG] batch key rotation template incorrect

### ISSUE THREAD

**Issue by poornas** [minio/docs#854]
**Describe the bug**
batch key rotation yaml should be output of `mc batch generate alias keyrotate`

**To Reproduce**
https://min.io/docs/minio/kubernetes/upstream/administration/batch-framework.html#sample-yaml-description-file-for-a-keyrotate-job-type

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ravindk89** [comment]
Ah, wrong include. i thought I caught this in my bug squashing tour but it might not have saved properly.

**Comment by ravindk89** [comment]
https://github.com/minio/docs/commit/840bd073ccbeb7470269f2f8e9f87c1de5e10028

**Comment by ravindk89** [comment]
Web should update in 5-10 min
