### ISSUE TITLE
[BUG] Configured is misspelled on mc-support-proxy page

### ISSUE THREAD

**Issue by fredrikcarlbom** [minio/docs#855]
**Describe the bug**
Configured is misspelled on https://min.io/docs/minio/linux/reference/minio-mc/mc-support-proxy.html

**To Reproduce**
1. Go to https://min.io/docs/minio/linux/reference/minio-mc/mc-support-proxy.html
2. The topic 'Remove the Proxy URL Congifugred for a Deployment' is misspelled

**Expected behavior**
Configured should not be misspelled

**Comment by ravindk89** [comment]
Closed by #856
