### ISSUE TITLE
[BUG] Issue with Deprecation notice Alignment

### ISSUE THREAD

**Issue by bexsoft** [minio/docs#857]
**Describe the bug**
There is an issue with Legacy deprecation notice where the Click to Show label & the title are not vertical aligned

**To Reproduce**
Go to https://min.io/docs/minio/linux/administration/identity-access-management/minio-user-management.html & look for `MinIO root user` section.

**Expected behavior**
Text block should be vertical aligned and had equal padding on the top & bottom of the box.

**Screenshots**
<img width="841" alt="Screenshot 2023-05-17 at 12 24 45" src="https://github.com/minio/docs/assets/33497058/12872a6c-8f99-4000-86ec-4825c14cfc92">

**Comment by feorlen** [comment]
No `:yeet-into-sun:` emoji, GitHub? I has a sad.

**Comment by rushenn** [comment]
> @rushenn if you would be so kind as to look at the CSS/SCSS issue?
> 
> @djwfyi @feorlen it's been over 2 years since the deprecation of the legacy root envvars. Objections to simply removing them and any references from our documentation?

Taking a look @ravindk89
