### ISSUE TITLE
Can't define policy with ExistingObjectTag on PUT object

### ISSUE THREAD

**Issue by sushiMix** [minio/docs#872]
## Expected Behavior

Being able to apply rights as described in the documentation: https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#supported-s3-policy-condition-keys with PutObject / PutObjectTagging 

## Current Behavior
Trying to submit the following policy :
`
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": ["s3:GetBucketLocation", "s3:HeadBucket", "s3:ListBucket"],
        "Resource": "arn:aws:s3:::test"
      },
      {
        "Effect": "Allow",
        "Action": ["s3:GetObject"],
        "Resource": "arn:aws:s3:::test/*"
      },
      {
        "Effect": "Deny",
        "Action": ["s3:PutObjectTagging", "s3:PutObject"],
        "Resource": "arn:aws:s3:::test/*",
        "Condition": {
            "StringEquals":
              {"s3:ExistingObjectTag/sealed": "on"}
          }
      }
  ]
}
`

Fails with : 

> There was an error creating a Policy: unsupported condition keys '[s3:ExistingObjectTag/sealed]' used for action 's3:PutObject'. Please check Policy syntax.

## Possible Solution
Update the documentation or code.

## Steps to Reproduce (for bugs)

1. Open the mini console
2. Try to submit the policy in the current behavior description.

## Context
Trying to use object tagging to avoid put on message (versioning mgt is too heavy/complex for our use case).

## Regression
Don't know as my previous version of minio does not support it.

## Your Environment

* mini docker image RELEASE.2023-05-04T21-44-30Z
* single node server.

**Comment by ravindk89** [comment]
https://github.com/minio/pkg/blob/main/iam/policy/action.go#L372-L385

Aha - so it looks like we support `s3:RequestObjectTag` and `s3:RequestObjectTagKeys` , which are defined [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/list_amazons3.html), but not `ExistingObjectTag`. So can update to cover both in one go.
