### ISSUE TITLE
Deploy MinIO: Multi-Node Multi-Drive doc fixes for /etc/fstab and update service and config from github...

### ISSUE THREAD

**Issue by raghav-vk** [minio/docs#874]
**Describe the bug**
While helping one of our customers, we found that `/etc/fstab` config causes the i3.en instances to enter into an emergency mode due to mount issues on AWS.

Fix the document to include nofail to `/etc/fstab` config.

```
# <file system>  <mount point>  <type>  <options>         <dump>  <pass>
  LABEL=DISK1      /mnt/disk1     xfs     defaults,noatime,nofail  0       2
  LABEL=DISK2      /mnt/disk2     xfs     defaults,noatime,nofail  0       2
  LABEL=DISK3      /mnt/disk3     xfs     defaults,noatime,nofail  0       2
  LABEL=DISK4      /mnt/disk4     xfs     defaults,noatime,nofail  0       2
```
Also please refresh minio service and minio config parts from the github config.

Also, please update 
**To Reproduce**
This occurs with i3.en instances on AWS.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Ephemeral instances on AWS should not be restarted, if done the data loss is expected. So, not a normal case to dictate the change. But something they need to be aware off.

**Comment by ravindk89** [comment]
https://github.com/minio/minio-service/commit/36832b7f23d227df796a9b7a574bbc3db0855a66 SACRED CONTEXT

**Comment by djwfyi** [comment]
https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html
