### ISSUE TITLE
[BUG] mc mirror --limit-download misses mention of MBps/ MiBps

### ISSUE THREAD

**Issue by KaliszAd** [minio/docs#902]
**Describe the bug**
mc mirror --limit-download misses mention of MBps/ MiBps e.g `mc mirror --limit-download 10M <source> <dest>` seems to work as expected. For many purposes MBps seems like the most useful unit that you would want to limit to.

**Comment by ravindk89** [comment]
https://min.io/docs/minio/linux/reference/minio-mc/mc-mirror.html#mc.mirror.-limit-download

Indeed we missed the M, and arguably we could include P and E but I would love to see first the deployment with those kinds of upload speeds.
