### ISSUE TITLE
[RELEASE] MinIO SERVER RELEASE.2023-06-29T05-12-28Z

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#909]
See https://github.com/minio/minio/releases/tag/RELEASE.2023-06-29T05-12-28Z for full release notes

- [ ] ~New Lifecycle Config `ExpiredObjectAllVersions` in [PR17521](https://github.com/minio/minio/pull/17521)~ 
  ~However, this is not in `mc` yet, so might not be documentable - or would require creating a JSON rule and importing it from there~
- [ ] We now allow site replication for non-distributed (SNSD/SNMD) setups [PR 17524](https://github.com/minio/minio/pull/17524). We could make a simple note of this as a "You can do this in testing, but not recommended in production"
- [x] We could note that we now log "skipped" files in decommissioning as part of logging [PR 17522](https://github.com/minio/minio/pull/17522)

**Comment by feorlen** [comment]
https://github.com/minio/minio/pull/17524 is noted as a bug fix, possibly for an edge case with test environments and multiple containers from the same image? The reported issue is a recent regression, unclear what/if docs changes are appropriate. Is there something helpful to say?

**Comment by feorlen** [comment]
Engineering intends to update `mc ilm rule` so users won't need to import JSON to get the https://github.com/minio/minio/pull/17521 functionality.
