### ISSUE TITLE
OIDC dynamic redirect URI env var does not work

### ISSUE THREAD

**Issue by PKizzle** [minio/docs#913]
## Expected Behavior
MinIO Console shall use the Host header of the originating request to construct the redirect URI passed to the OIDC provider if the environment variable `MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC` is set to `true` (as documented [here](https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC)).

## Current Behavior
Instead MinIO creates a new OIDC configuration named `DYNAMIC` where the redirect URI is set to `true`.

## Steps to Reproduce (for bugs)
1. Use the official minio helm chart and add  `MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC: "true"` to the environment section
2. Install the helm chart
3. Check the OIDC configuration in the console or by using `mc`

## Context
I am using MinIO behind a reverse proxy so I need to enable the mentioned setting.

## Regression
Unknown.

## Your Environment
* Version used: RELEASE.2023-07-07T07-13-57Z
* Server setup and configuration: MinIO helm chart 5.0.11 on a 1.27.2 k3s cluster (3x RaspberryPi 4B)
* Operating System and version: 6.1.21-v8+ aarch64 GNU/Linux

**Comment by ravindk89** [comment]
https://github.com/minio/docs/commit/9af4c2ccdf3ce4db9e03eb6054e4e95c10125e65 should be updated live hsortly.

**Comment by PKizzle** [comment]
Thank you for the quick response. Sadly, when using `on` for the environment variable it is not correctly set in the UI.

**Comment by harshavardhana** [comment]
> Thank you for the quick response. Sadly, when using `on` for the environment variable it is not correctly set in the UI.

Please open an issue in Console UI project @PKizzle
