### ISSUE TITLE
[BUG] Superfluous `Optional` below mc version commands

### ISSUE THREAD

**Issue by krisis** [minio/docs#918]
**Describe the bug**
We can see the word `Optional` below each of the version commands enable, info and suspend. These commands are not optional.
![image](https://github.com/minio/docs/assets/522593/82d67dbd-dfe4-4086-9269-aa320238a4b0)

**Expected behavior**
We shouldn't have the word `Optional` below these version commands.

**Comment by feorlen** [comment]
This is a followup from https://github.com/minio/docs/pull/917

**Comment by feorlen** [comment]
The usual pattern is to have either _required_ or _optional_. In this case one and only one of the three (enable, suspend, info) must be specified, which doesn't quite fit that way.

**Comment by ravindk89** [comment]
Best thing to do here is to break it up into subcommands as we do on other pages. So

```
mc-version.rst
mc-version-enable.rst
mc-version-suspend.rst
mc-version-info.rst

```

**Comment by feorlen** [comment]
@krisis I'm going to stick this back in _To Do_ for a bit, while I finish some other things. Splitting up the page is difficult, just takes a little longer.
