### ISSUE TITLE
[RELEASE] MinIO Server RELEASE.2023-07-07T07-13-57Z, RELEASE.2023-07-11T21-29-34Z

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#922]
See 
- https://github.com/minio/minio/releases/tag/RELEASE.2023-07-07T07-13-57Z 
- https://github.com/minio/minio/releases/tag/RELEASE.2023-07-11T21-29-34Z

for full release notes

# RELEASE.2023-07-07T07-13-57Z 

- [x] Adds support for perf tests in site replication configs - [PR17477](https://github.com/minio/minio/pull/17477) 

  Has `mc` component but not clear how this works in practice

# RELEASE.2023-07-11T21-29-34Z

- [ ] Metrics might have shifted slightly, need to test and confirm via [PR17627](https://github.com/minio/minio/pull/17627) and [PR17594](https://github.com/minio/minio/pull/17594)

Worth noting that https://github.com/minio/minio/pull/17663 is going to change metrics around a lot too. Might not be worth looking into these changes until the bucket metric migration occurs, and then doing a pass overall

**Comment by harshavardhana** [comment]
> * Has `mc` component but not clear how this works in practice

You are basically testing site-to-site network tests @ravindk89

**Comment by harshavardhana** [comment]
it is currently hidden, and it is not run when `mc support perf` runs. Because it requires site replication to be configured.

**Comment by harshavardhana** [comment]
> [ ] Metrics might have shifted slightly, need to test and confirm via [PR17627](https://github.com/minio/minio/pull/17627) and [PR17594](https://github.com/minio/minio/pull/17594)

They have not @ravindk89

**Comment by ravindk89** [comment]
@harshavardhana do we intend to document the site-replication mc command at this time at all? We also hide help outputs for the other perf subcommands,.

**Comment by djwfyi** [comment]
#17477 was done in #964
