### ISSUE TITLE
[RELEASE] mc MULTIPLE VERSIONS

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#930]
# [RELEASE.2023-07-21T20-44-27Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-07-21T20-44-27Z)

- [x] (OPTIONAL) `mc admin info` includes version/delete marker information [PR4642](https://github.com/minio/mc/pull/4642)
- [x] `mc admin prometheus metrics` now supports cluster, node, and bucket metrics [PR4632](https://github.com/minio/mc/pull/4632)

# [RELEASE.2023-07-18T21-05-38Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-07-18T21-05-38Z)

- [x] `mc replicate diff` -> `mc replicate backlog` [PR4568](https://github.com/minio/mc/pull/4568)
- [x] Add `mc support top net` [PR4626](https://github.com/minio/mc/pull/4626)
- [ ] 

# [RELEASE.2023-07-11T23-30-44Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-07-11T23-30-44Z)

- [x] No updates which require documentation
 
# [RELEASE.2023-07-07T05-25-51Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-07-07T05-25-51Z)

- [x] New support command for replication performance testing [PR4609](https://github.com/minio/mc/pull/4608)
- [x] `mc replicate ... --sync` flag deprecated, move to `--mode` [PR 4623](https://github.com/minio/mc/pull/4623)
- [x] `mc admin user info` can return metadata for internal/external users [PR 4613](https://github.com/minio/mc/pull/4613)

# [RELEASE.2023-06-28T21-54-17Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-06-28T21-54-17Z)

- [x] No updates which require documentation

# [RELEASE.2023-06-23T18-12-07Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-06-23T18-12-07Z)

- [ ] Optional + test, all mc CLI commands should return help if entered w/ no params [PR4609](https://github.com/minio/mc/pull/4609)

# [RELEASE.2023-06-19T19-31-19Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-06-19T19-31-19Z)

- [x] No updates which require documentation

# [RELEASE.2023-06-15T15-08-26Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-06-15T15-08-26Z)

- [x] No updates which require documentation

**Comment by djwfyi** [comment]
I'm working on 4632 while adding Grafana info.

**Comment by ravindk89** [comment]
Quick test indicates the auto-help works as long as you get the right root.
