### ISSUE TITLE
[BUG] Trailing slash for console access via NGNIX

### ISSUE THREAD

**Issue by tariver** [minio/docs#957]
**Describe the bug**
Multi-node MinIO installation doesn't open console if proxied behind NGNIX

**To Reproduce**
1. Install MinIO in multi-node mode
2. Configure NGINX to access MinIO using this guide - https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html
3. Try to access MinIO via `minio.example.net/minio/ui` (note that there is no trailing slash)
4. There is just white screen, similar to minio/console#2766

**Expected behavior**
Browser should be redirected to `minio.example.net/minio/ui/login`

But if you try to access `minio.example.net/minio/ui/` (note the trailing slash) you are redirected to `minio.example.net/minio/ui/login`
MinIO server version is the latest - `RELEASE.2023-08-16T20-17-30Z`

I'm not sure if this is a bug or a error in documentation (#921).

**Comment by ravindk89** [comment]
I think this is expected?

```
rewrite ^/minio/ui/(.*) /$1 break;
```

this captures `/minio/ui/` as the base URL and substitutes everything in the capture group only. 

So, if I understand it correctly:

```
minio.example.net/minio/ui/<foo>
```

nginx should proxy that as just `<foo>`.

So if you go to minio.example.net/minio/ui <- there's nothing here that gets captured, and I'm guessing nginx attempts to proxy back what is effectively a blank string.

I think the appropriate fix is to note that the proxy URL should include the trailing slash. NGINX is not our product so if someone in the community wants to experiment and see if they can come up with a more applicable `rewrite` rule we'd be happy to take that in.

**Comment by tariver** [comment]
I was able to fix it, you have to add a trailing slash to the _location_.
```nginx
   location /minio/ui/ {
      rewrite ^/minio/ui/(.*) /$1 break;
```

From [NGINX documentation](http://nginx.org/en/docs/http/ngx_http_core_module.html#location):
> If a location is defined by a prefix string that ends with the slash character, and requests are processed by one of proxy_pass, fastcgi_pass, uwsgi_pass, scgi_pass, memcached_pass, or grpc_pass, then the special processing is performed. In response to a request with URI equal to this string, but without the trailing slash, a permanent redirect with the code 301 will be returned to the requested URI with the slash appended.

I've created a pull request to update the documentation.
