### ISSUE TITLE
Document the MinIO Operator init container

### ISSUE THREAD

**Issue by feorlen** [minio/docs#968]
Operator uses an init container to perform some initialization for each new pod. There isn't any documentation about what it does, would be nice to have some.

**Goals**

- [ ] Basic info on what the Operator init container does.
- [ ] Maybe: additional detail on how to use your own (additional) init container.

**Non-Goals**

Detail on how to create the container itself.

**Additional context**

Kubernetes docs: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
@cniackz has some detail about the Operator container, not sure where.
Related to https://github.com/minio/docs/pull/967

**Comment by djwfyi** [comment]
Document as part of a k8s/Operator core concept doc.
