### ISSUE TITLE
[BUG] Link not working on Bucket Notifications page

### ISSUE THREAD

**Issue by wdinyes** [minio/docs#984]
**Describe the bug**
The link to the ListenNotification doc in the Global Events section is appearing as text, not a link.

**To Reproduce**
1. Go to '[Bucket Notifications > Global Events](https://min.io/docs/minio/linux/administration/monitoring/bucket-notifications.html#global-events)'
2. In the first paragraph under Global Events, the link to ListenNotification is not working.

**Expected behavior**
I'd love a link, of course.

**Screenshots**
<img width="803" alt="Screenshot 2023-09-01 at 11 04 15 AM" src="https://github.com/minio/docs/assets/25906104/1758e426-ca82-43fc-b5f0-5b1fc526f4e6">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 116.0.5845.110

**Comment by ravindk89** [comment]
Should be fixed - rebuilds usually take a few minutes.
